/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Principal;

import ConectaBanco.ConexaoBD;
import Controle.Janelas;
import ModeloBeans.BeansPedido;
import ModeloBeans.ModeloTabela;
import ModeloDao.DaoNota;
import ModeloDao.DaoPedido;
import View.Empresa.AddEmpresa;
import Teste.ResetTabelas;
import View.Expedicao.JDialogExpedicao;
import View.Pedido.AddPedido2;
import java.awt.CardLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.math.BigDecimal;
import java.sql.SQLException;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.RowSorter;
import javax.swing.SwingConstants;
import javax.swing.Timer;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author edson
 */
public class Menu extends javax.swing.JFrame {
// Chama conexao

    ConexaoBD conex = new ConexaoBD();
    // chaama janelas
    Janelas janela = new Janelas();
    Login log = new Login(this, rootPaneCheckingEnabled);
//    ListaUsuario lista_usuario = new ListaUsuario();
//    ListaUnidade lista_unidade = new ListaUnidade();
//    ListaFornecedor lista_fornecedor = new ListaFornecedor();
//    ListaCliente lista_cliente = new ListaCliente();
//    ListaProduto lista_produto = new ListaProduto();
//    AddProtocolo add_prot = new AddProtocolo();
//    ListaCfop lista_cfop = new ListaCfop();

    //
    String MenuMinhaData, MenuMinhaDataSistema, MenuMinhaHora, MinhaEmpresa, MeuCnpj, MinhaVersao = "1.0", resposta = "";
    CardLayout cl;

    /**
     * Creates new form Teste
     */
    public Menu() {
        initComponents();

        HoraAtual();
        //log.setVisible(true);
        ValidaLogin();
        ChamaEmpresa();
        cl = (CardLayout) jPanel_principal.getLayout();
//        cl.removeLayoutComponent(jPanel_tela1);
//        cl.removeLayoutComponent(jPanel_tela2);
    }

    public void IniciaPedido() {
        janela.Chama_add_pedido_iniciar();
    }

    public void ChamaEmpresa() {
        conex.conexao();
        conex.executaSql2("SELECT  empresa_descricao ,empresa_cnpj FROM tbl_empresa where empresa_id is not null and empresa_id !=0 order by empresa_id asc ");
        try {
            conex.rs.last();
            MinhaEmpresa = conex.rs.getString("empresa_descricao");
            MeuCnpj = conex.rs.getString("empresa_cnpj");
            if (MeuCnpj.replace(".", "").replace("/", "").replace("-", "").trim().isEmpty()) {
                MeuCnpj = "";
            } else {
                MeuCnpj = " Cnpj " + MeuCnpj;
            }
            this.setTitle("SIES " + MinhaVersao + " -  " + MinhaEmpresa + " " + MeuCnpj);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Não foi encontrado uma empresa !");
        }
        conex.desconecta();

    }

    public void ValidaLogin() {

        int perm = Integer.parseInt(jLabelPermissao.getText());
        if (perm == 0) {
            jMenuItem2.setEnabled(true);
            jMenu6.setEnabled(true);
        } else if (perm == 1) {
            jMenuItem2.setEnabled(false);
            jMenu6.setEnabled(false);
        } else {
            jMenuItem2.setEnabled(false);
            jMenu6.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_inferior = new javax.swing.JPanel();
        jLabelHora = new javax.swing.JLabel();
        jLabelData = new javax.swing.JLabel();
        jLabelPermissao = new javax.swing.JLabel();
        jLabelIdUsuario = new javax.swing.JLabel();
        jLabel_Password = new javax.swing.JLabel();
        jLabelUsuario = new javax.swing.JButton();
        jPanel_principal = new javax.swing.JPanel();
        jPanel_tela1 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel_principal = new javax.swing.JLabel();
        jPanel_tela2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jT_PedidoA = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jT_PedidoB = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jPanel_tela3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Lista = new javax.swing.JTable();
        jTextField_busca = new javax.swing.JTextField();
        jB_busca = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel_tela4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jT_PedidoA2 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jT_PedidoB2 = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jT_Expedicao = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jT_Saidas = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem20 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenuItem21 = new javax.swing.JMenuItem();
        jMenuItem22 = new javax.swing.JMenuItem();
        jMenu10 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenuItem19 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SIES 1.0");

        jPanel_inferior.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelHora.setText("00:00:00");

        jLabelData.setText("00/00/0000");

        jLabelPermissao.setText("0");

        jLabelIdUsuario.setText("0");

        jLabel_Password.setText("0");

        jLabelUsuario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelUsuario.setText(" ");
        jLabelUsuario.setBorder(null);
        jLabelUsuario.setBorderPainted(false);
        jLabelUsuario.setDefaultCapable(false);
        jLabelUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelUsuarioMouseClicked(evt);
            }
        });
        jLabelUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLabelUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_inferiorLayout = new javax.swing.GroupLayout(jPanel_inferior);
        jPanel_inferior.setLayout(jPanel_inferiorLayout);
        jPanel_inferiorLayout.setHorizontalGroup(
            jPanel_inferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_inferiorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel_Password, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelIdUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelPermissao, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelData, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelHora)
                .addContainerGap())
        );
        jPanel_inferiorLayout.setVerticalGroup(
            jPanel_inferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_inferiorLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel_inferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelHora, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                    .addComponent(jLabelData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelPermissao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_Password, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelIdUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelUsuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jPanel_principal.setBackground(new java.awt.Color(0, 0, 0));
        jPanel_principal.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel_principal.setLayout(new java.awt.CardLayout());

        jPanel_tela1.setBackground(new java.awt.Color(204, 204, 255));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel_principal.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel_principal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_principal, javax.swing.GroupLayout.DEFAULT_SIZE, 988, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_principal, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel_tela1Layout = new javax.swing.GroupLayout(jPanel_tela1);
        jPanel_tela1.setLayout(jPanel_tela1Layout);
        jPanel_tela1Layout.setHorizontalGroup(
            jPanel_tela1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_tela1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel_tela1Layout.setVerticalGroup(
            jPanel_tela1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_tela1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel_principal.add(jPanel_tela1, "tela1");

        jPanel_tela2.setBackground(java.awt.Color.green);

        jT_PedidoA.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jT_PedidoA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jT_PedidoAMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jT_PedidoA);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Lista de pedidos ativos");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel3.setText("...");

        jT_PedidoB.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jT_PedidoB);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Lista de pedidos prontos");

        javax.swing.GroupLayout jPanel_tela2Layout = new javax.swing.GroupLayout(jPanel_tela2);
        jPanel_tela2.setLayout(jPanel_tela2Layout);
        jPanel_tela2Layout.setHorizontalGroup(
            jPanel_tela2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_tela2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_tela2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_tela2Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel_tela2Layout.createSequentialGroup()
                        .addGroup(jPanel_tela2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 506, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel_tela2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 506, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
        );
        jPanel_tela2Layout.setVerticalGroup(
            jPanel_tela2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_tela2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_tela2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_tela2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3))
        );

        jPanel_principal.add(jPanel_tela2, "tela2");

        jTable_Lista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable_Lista);

        jTextField_busca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_buscaKeyPressed(evt);
            }
        });

        jB_busca.setText("Busca");
        jB_busca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_buscaActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Consulta entrada de produtos");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 492, Short.MAX_VALUE)
                        .addComponent(jTextField_busca, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jB_busca))
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 419, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_busca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB_busca))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel_tela3Layout = new javax.swing.GroupLayout(jPanel_tela3);
        jPanel_tela3.setLayout(jPanel_tela3Layout);
        jPanel_tela3Layout.setHorizontalGroup(
            jPanel_tela3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_tela3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel_tela3Layout.setVerticalGroup(
            jPanel_tela3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_tela3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel_principal.add(jPanel_tela3, "tela3");

        jPanel_tela4.setBackground(new java.awt.Color(204, 204, 255));

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));

        jPanel4.setBackground(new java.awt.Color(51, 51, 255));
        jPanel4.setPreferredSize(new java.awt.Dimension(300, 200));

        jT_PedidoA2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jT_PedidoA2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jT_PedidoA2MouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jT_PedidoA2);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Pedidos ativos");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(204, 0, 255));
        jPanel5.setPreferredSize(new java.awt.Dimension(300, 200));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Ultimas entradas");

        jT_PedidoB2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(jT_PedidoB2);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(15, 15, 15)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jPanel6.setBackground(new java.awt.Color(255, 51, 51));
        jPanel6.setPreferredSize(new java.awt.Dimension(300, 200));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Expedição");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        jT_Expedicao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jT_Expedicao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jT_ExpedicaoMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(jT_Expedicao);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel7.setBackground(new java.awt.Color(51, 255, 51));
        jPanel7.setPreferredSize(new java.awt.Dimension(300, 200));
        jPanel7.setRequestFocusEnabled(false);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Ultimas saidas");

        jT_Saidas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane7.setViewportView(jT_Saidas);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 496, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 496, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 496, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 496, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel4.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout jPanel_tela4Layout = new javax.swing.GroupLayout(jPanel_tela4);
        jPanel_tela4.setLayout(jPanel_tela4Layout);
        jPanel_tela4Layout.setHorizontalGroup(
            jPanel_tela4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_tela4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel_tela4Layout.setVerticalGroup(
            jPanel_tela4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_tela4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel_principal.add(jPanel_tela4, "tela4");

        jMenuBar1.setForeground(new java.awt.Color(153, 255, 153));

        jMenu1.setText("Arquivo");

        jMenuItem12.setText("Dashboard");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem12);

        jMenuItem1.setText("Sair");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem15.setText("papel de parede");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem15);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu4.setText("Cadastros");

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setText("1-Unidades");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem3);

        jMenuItem7.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem7.setText("2-Produtos");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem7);

        jMenuItem8.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_3, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem8.setText("3-Fornecedores");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem8);

        jMenuItem9.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_4, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem9.setText("4-Clientes");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem9);

        jMenuItem16.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_5, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem16.setText("5-Cfop");
        jMenuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem16ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem16);

        jMenuBar1.add(jMenu4);

        jMenu9.setText("Consultas");

        jMenuItem4.setText("Entradas");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu9.add(jMenuItem4);

        jMenuItem10.setText("Pedidos");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu9.add(jMenuItem10);

        jMenuItem5.setText("Saidas");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu9.add(jMenuItem5);

        jMenuItem11.setText("DashBoard");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu9.add(jMenuItem11);

        jMenuBar1.add(jMenu9);

        jMenu8.setText("Entradas");

        jMenuItem14.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem14.setText("Nota entrada");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem14);

        jMenuItem20.setText("Protocolo entrada");
        jMenuItem20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem20ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem20);

        jMenuBar1.add(jMenu8);

        jMenu3.setText("Pedidos");

        jMenuItem17.setText("Novo pedido");
        jMenuItem17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem17ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem17);

        jMenuItem21.setText("Lista de pedidos");
        jMenuItem21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem21ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem21);

        jMenuItem22.setText("Novo pedido");
        jMenuItem22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem22ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem22);

        jMenuBar1.add(jMenu3);

        jMenu10.setText("Saidas");
        jMenuBar1.add(jMenu10);

        jMenu5.setText("Relatórios");
        jMenuBar1.add(jMenu5);

        jMenu6.setText("Configurações");

        jMenuItem2.setText("1-Usuários");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem2);

        jMenuItem13.setText("2-Empresa");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem13);
        jMenu6.add(jSeparator1);

        jMenu7.setText("0-Testes");

        jMenuItem6.setText("1-Resetar tabelas");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem6);

        jMenu6.add(jMenu7);

        jMenuItem18.setText("Tela");
        jMenuItem18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem18ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem18);

        jMenuItem19.setText("Menu1");
        jMenuItem19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem19ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem19);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel_inferior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel_principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_inferior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        log.setVisible(true);
        ValidaLogin();
        ChamaEmpresa();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        janela.Chama_lista_usuario();
//        lista_usuario.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
//        lista_unidade.ValidaPermissao();
//        lista_unidade.setVisible(true);
        janela.Chama_lista_unidade();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        ResetTabelas reset = new ResetTabelas();
        reset.setVisible(true);

    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
//        lista_fornecedor.ValidaPermissao();
//        lista_fornecedor.setVisible(true);
        janela.Chama_lista_fornecedor();
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed

//        lista_cliente.ValidaPermissao();
//        lista_cliente.setVisible(true);
        janela.Chama_lista_cliente();
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        AddEmpresa add = new AddEmpresa(this, rootPaneCheckingEnabled);
        add.setVisible(true);
        ChamaEmpresa();
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
//        lista_produto.ValidaPermissao();
//        lista_produto.setVisible(true);
        janela.Chama_lista_produto();
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
//        lista_nota.ValidaPermissao();
//        lista_nota.setVisible(true);
        janela.Chama_lista_nota();
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jMenuItem16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem16ActionPerformed
//        lista_cfop.ValidaPermissao();
//        lista_cfop.setVisible(true);
        janela.Chama_lista_cfop();
    }//GEN-LAST:event_jMenuItem16ActionPerformed

    private void jMenuItem18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem18ActionPerformed
        Tela tela = new Tela();
        tela.setVisible(true);
    }//GEN-LAST:event_jMenuItem18ActionPerformed

    private void jMenuItem19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem19ActionPerformed
        Menu1 menu1 = new Menu1();
        menu1.setVisible(true);
    }//GEN-LAST:event_jMenuItem19ActionPerformed

    private void jMenuItem20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem20ActionPerformed

        janela.Chama_lista_protocolo();


    }//GEN-LAST:event_jMenuItem20ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
//        cl = (CardLayout) jPanel_principal.getLayout();
//        jPanel_principal.remove(jPanel_tela1);
//        jPanel_principal.add(jPanel_tela1, "tela1");
//        cl.removeLayoutComponent(jPanel_tela1);
//        cl.addLayoutComponent("tela1", jPanel_tela1);
        cl.show(jPanel_principal, "tela3");

    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
//        CardLayout cl = (CardLayout) jPanel_principal.getLayout();
//jPanel_principal.add(jPanel_tela1, "tela2");
//        cl.removeLayoutComponent(jPanel_tela2);
//        cl.addLayoutComponent("tela2", jPanel_tela2);
        cl.show(jPanel_principal, "tela2");
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
//        jPanel_principal.removeAll();jPanel_principal.validate();
//jPanel_tela1.setVisible(false);
//        cl.removeLayoutComponent(jPanel_tela1);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        cl.show(jPanel_principal, "tela4");

    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        cl.show(jPanel_principal, "tela1");
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jB_buscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_buscaActionPerformed
        PreencheTabela();
        jTextField_busca.requestFocus();
    }//GEN-LAST:event_jB_buscaActionPerformed

    private void jTextField_buscaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_buscaKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            jB_busca.doClick();
        }
    }//GEN-LAST:event_jTextField_buscaKeyPressed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
        jLabel_principal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Desert.jpg")));
        jLabel_principal.setHorizontalAlignment((int) CENTER_ALIGNMENT);
        jLabel_principal.setVerticalAlignment((int) CENTER_ALIGNMENT);
        jLabel_principal.setSize(WIDTH, HEIGHT);

    }//GEN-LAST:event_jMenuItem15ActionPerformed

    private void jMenuItem17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem17ActionPerformed
        janela.Chama_add_pedido_iniciar();
    }//GEN-LAST:event_jMenuItem17ActionPerformed

    private void jMenuItem22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem22ActionPerformed
        janela.Chama_add_pedido(0);
    }//GEN-LAST:event_jMenuItem22ActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        PreencheTabela_Ativo();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jT_PedidoAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jT_PedidoAMouseClicked
        PreencheTabela_UltimasEntradas();
    }//GEN-LAST:event_jT_PedidoAMouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        PreencheTabela_Ativo();
        PreencheTabela_Expedicao();
        PreencheTabela_UltimasEntradas();

    }//GEN-LAST:event_jLabel5MouseClicked

    private void jT_PedidoA2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jT_PedidoA2MouseClicked
        String St = "0";
        int Id = 0;
        int se = 0;
        try {
            St = "" + jT_PedidoA2.getValueAt(jT_PedidoA2.getSelectedRow(), 1);
            Id = (int) jT_PedidoA2.getValueAt(jT_PedidoA2.getSelectedRow(), 0);
            se = 1;
        } catch (Exception e) {
        }

        if (evt.getClickCount() == 2) {
            if (evt.getButton() == MouseEvent.BUTTON1) {
                if (St.equals("Em edição")) {
                    se = JOptionPane.showConfirmDialog(null, "Deseja editar o pedido " + Id + " ?", "Editar", JOptionPane.YES_NO_OPTION);
                    if (se == 0) {

                        janela.Chama_add_pedido(Id);
                        PreencheTabela_Ativo();
                        PreencheTabela_Expedicao();
                        PreencheTabela_UltimasEntradas();
                    }
                }
                if (St.equals("Em produção")) {
                    se = JOptionPane.showConfirmDialog(null, "Deseja finalizar o pedido " + Id + " ?", "Finalizar", JOptionPane.YES_NO_OPTION);
                    if (se == 0) {
                        BeansPedido BP = new BeansPedido();
                        DaoPedido DP = new DaoPedido();
                        BP.setId_pedido(Id);
                        BP.setPedido_status(6);
                        DP.ProcessarExpedicao(BP);
                    }
                }
            }
            if (evt.getButton() == MouseEvent.BUTTON3) {
                if (St.equals("Em produção")) {
                    se = JOptionPane.showConfirmDialog(null, "Deseja colocar o pedido  " + Id + " em edição ?", "Retornar operação", JOptionPane.YES_NO_OPTION);
                    if (se == 0) {
                        BeansPedido BP = new BeansPedido();
                        DaoPedido DP = new DaoPedido();
                        BP.setId_pedido(Id);
                        BP.setPedido_status(9);
                        DP.ProcessarRetornoParaEdicao(BP);
                    }
                }
            }
            PreencheTabela_Ativo();
            PreencheTabela_Expedicao();
            PreencheTabela_UltimasEntradas();
        }

        System.out.println("s " + se);
    }//GEN-LAST:event_jT_PedidoA2MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        PreencheTabela_Expedicao();
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jMenuItem21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem21ActionPerformed
        janela.Chama_lista_pedido();
    }//GEN-LAST:event_jMenuItem21ActionPerformed

    private void jT_ExpedicaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jT_ExpedicaoMouseClicked

        String St = "" + jT_Expedicao.getValueAt(jT_Expedicao.getSelectedRow(), 1);
        int Id = (int) jT_Expedicao.getValueAt(jT_Expedicao.getSelectedRow(), 0);
        int se = 1;
        if (evt.getClickCount() == 2) {

            if (St.equals("Pronto")) {
                se = JOptionPane.showConfirmDialog(null, "Deseja manipular o pedido " + Id + " ?", "Expedição", JOptionPane.YES_NO_OPTION);
                if (se == 0) {
                    JDialogExpedicao expedicao = new JDialogExpedicao(this, rootPaneCheckingEnabled);
                    expedicao.Recebe(Id, St);
                    expedicao.setVisible(true);
                }
            } if (St.equals("Aguardando")) {
                se = JOptionPane.showConfirmDialog(null, "Deseja manipular o pedido " + Id + " ?", "Expedição", JOptionPane.YES_NO_OPTION);
                if (se == 0) {
                    JDialogExpedicao expedicao = new JDialogExpedicao(this, rootPaneCheckingEnabled);
                    expedicao.Recebe(Id, St);
                    expedicao.setVisible(true);
                }
            }

            PreencheTabela_Ativo();
            PreencheTabela_Expedicao();
            PreencheTabela_UltimasEntradas();
        }

        System.out.println("s " + se);
    }//GEN-LAST:event_jT_ExpedicaoMouseClicked

    private void jLabelUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLabelUsuarioActionPerformed
        PreencheTabela_Ativo();
        PreencheTabela_Expedicao();
        PreencheTabela_UltimasEntradas();
        PreencheTabela_UltimasSaidas();
//        JOptionPane.showMessageDialog(rootPane, "aqui");
    }//GEN-LAST:event_jLabelUsuarioActionPerformed

    private void jLabelUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelUsuarioMouseClicked
        PreencheTabela_Ativo();
        PreencheTabela_Expedicao();
        PreencheTabela_UltimasEntradas();
    }//GEN-LAST:event_jLabelUsuarioMouseClicked
    public void PreencheTabela() {
        resposta = jTextField_busca.getText();
        ArrayList dados = new ArrayList();
        String[] colunas = new String[]{"Codigo", "Data", "Documento", "Fornecedor", "Produto", "Complemento", "Un", "Valor R$", "Quantidade"};
        conex.conexao();

        conex.executaSql2("  SELECT produto_id, produto_descricao, sigla_unidade, produto_valor, item_id,   item_complemento, item_qtd,  \n"
                + "              item_nota_id, item_protocolo_id,protocolo_data,nota_data,b.fornecedor_nome as forn_n,a.fornecedor_nome as forn_p,protocolo_numero,nota_numero\n"
                + "  FROM public.tbl_item\n"
                + "  inner join tbl_produto on item_produto_id=produto_id\n"
                + "  inner join tbl_unidade on produto_unidade=id_unidade\n"
                + "  left join tbl_nota on id_nota=item_nota_id\n"
                + "  left join tbl_protocolo on id_protocolo=item_protocolo_id\n"
                + "  \n"
                + "   left join tbl_fornecedor as a on protocolo_id_fornecedor=fornecedor_id\n"
                + "   left join tbl_fornecedor as b on nota_id_fornecedor=b.fornecedor_id \n"
                + "  where (coalesce((sigla_unidade)) ||' '||coalesce((produto_descricao))\n"
                + "                ||' '||coalesce((item_complemento))||' '||coalesce((produto_registro ))||' '||coalesce((nota_data ),(protocolo_data ))"
                + "||' '||coalesce((a.fornecedor_nome ),(b.fornecedor_nome ))||' '||coalesce((protocolo_numero),(nota_numero))"
                + "ilike '%" + resposta + "%')    \n"
                + "  order by item_id  asc ");

        try {
            conex.rs.first();
            do {

                String MenuMeuValor = conex.rs.getString("produto_valor");
                Double num4 = (Double.parseDouble(MenuMeuValor));
                BigDecimal df1 = new BigDecimal(num4);
                NumberFormat nf1 = NumberFormat.getInstance();// getCurrencyInstance
                nf1.setMinimumFractionDigits(4);
                nf1.setMaximumFractionDigits(4);
                String FormatoValor = nf1.format(df1);

                String MenuMeuQtd = conex.rs.getString("item_qtd");
                Double num2 = (Double.parseDouble(MenuMeuQtd));
                BigDecimal df2 = new BigDecimal(num2);
                NumberFormat nf2 = NumberFormat.getInstance();// getCurrencyInstance
                nf2.setMinimumFractionDigits(4);
                nf2.setMaximumFractionDigits(4);
                String FormatoQtd = nf2.format(df2);

                // ,protocolo_numero,nota_numero
                int idnota = conex.rs.getInt("item_nota_id");
                System.out.println("idnota - " + idnota);
                int idprotocolo = conex.rs.getInt("item_protocolo_id");
                System.out.println("idprotocolo - " + idprotocolo);
                String forn, data, documento;

                if (idnota != 0) {
                    data = conex.rs.getString("nota_data");
                    forn = conex.rs.getString("forn_n");
                    documento = "Nota " + conex.rs.getString("nota_numero");
                } else if (idprotocolo != 0) {
                    data = conex.rs.getString("protocolo_data");
                    forn = conex.rs.getString("forn_p");
                    documento = "Protocolo " + conex.rs.getString("protocolo_numero");
                } else {
                    data = "erro data";
                    forn = "erro forn";
                    documento = "documento erro ";
                }

                System.out.println("data = " + data + " forn = " + forn);

                dados.add(new Object[]{conex.rs.getInt("item_id"), data, documento, forn,
                    conex.rs.getString("produto_descricao"), conex.rs.getString("item_complemento"), conex.rs.getString("sigla_unidade"),
                    FormatoValor, FormatoQtd});

            } while (conex.rs.next());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
            ///Logger.getLogger(UsuarioJIF.class.getName()).log(Level.SEVERE, null, ex);
        }
        ModeloTabela modelo = new ModeloTabela(dados, colunas);

        jTable_Lista.setModel(modelo);
        RowSorter<TableModel> sorter = new TableRowSorter<TableModel>(modelo);
        jTable_Lista.setRowSorter(sorter);
        jTable_Lista.getColumnModel().getColumn(0).setPreferredWidth(60);
        jTable_Lista.getColumnModel().getColumn(0).setResizable(true);
        jTable_Lista.getColumnModel().getColumn(1).setPreferredWidth(80);
        jTable_Lista.getColumnModel().getColumn(1).setResizable(true);
        jTable_Lista.getColumnModel().getColumn(2).setPreferredWidth(100);
        jTable_Lista.getColumnModel().getColumn(2).setResizable(true);
        jTable_Lista.getColumnModel().getColumn(3).setPreferredWidth(100);
        jTable_Lista.getColumnModel().getColumn(3).setResizable(true);
        jTable_Lista.getColumnModel().getColumn(4).setPreferredWidth(220);
        jTable_Lista.getColumnModel().getColumn(4).setResizable(true);
        jTable_Lista.getColumnModel().getColumn(5).setPreferredWidth(100);
        jTable_Lista.getColumnModel().getColumn(5).setResizable(true);
        jTable_Lista.getColumnModel().getColumn(6).setPreferredWidth(80);
        jTable_Lista.getColumnModel().getColumn(6).setResizable(true);
        jTable_Lista.getColumnModel().getColumn(7).setPreferredWidth(100);
        jTable_Lista.getColumnModel().getColumn(7).setResizable(true);
        jTable_Lista.getColumnModel().getColumn(8).setPreferredWidth(180);
        jTable_Lista.getColumnModel().getColumn(8).setResizable(true);

//  jTable_Lista.getColumnModel().getColumn(5).isCellVisible(false);
        jTable_Lista.getTableHeader().setReorderingAllowed(false);
        jTable_Lista.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        jTable_Lista.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        conex.desconecta();
        resposta = "";
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    public void DataAtual() {
        Date dataSistema = new Date();
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        SimpleDateFormat formato2 = new SimpleDateFormat("yyyy/MM/dd");
        MenuMinhaData = (formato.format(dataSistema));
        MenuMinhaDataSistema = (formato2.format(dataSistema));
        jLabelData.setText(MenuMinhaData);

//        System.out.println("Data - "+MenuMinhaData +" Hora - "+MenuMinhaHora);
    }

    public void HoraAtual() {
        Timer timer = new Timer(1000, new hora());
        timer.start();

//        DataAtual();
    }

    class hora implements ActionListener {

        String MenuMinhaHora;

        @Override
        public void actionPerformed(ActionEvent e) {
            Calendar now = Calendar.getInstance();
            MenuMinhaHora = (String.format("%1$tH:%1$tM:%1$tS", now));
            String MenuMinhaHoraSistema = (String.format("%1$tM:%1$tS", now));
            MenuMinhaHoraSistema = MenuMinhaHora.replace(":", "");
            jLabelHora.setText(MenuMinhaHora);
            DataAtual();
        }

    }

    public void PreencheTabela_Ativo() {

        DaoPedido DAOP = new DaoPedido();
        String[] colunas = new String[]{"Código ", "Status", "Data", "Cliente", "Observação", "Registro"};
        ArrayList dados;
        String b = resposta;
        dados = (ArrayList) DAOP.DashBoard_PreencheTabelaA2(b);
        ModeloTabela modelo = new ModeloTabela(dados, colunas);
        DefaultTableCellRenderer esquerda = new DefaultTableCellRenderer();
        DefaultTableCellRenderer centralizado = new DefaultTableCellRenderer();
        DefaultTableCellRenderer direita = new DefaultTableCellRenderer();
        esquerda.setHorizontalAlignment(SwingConstants.LEFT);
        centralizado.setHorizontalAlignment(SwingConstants.CENTER);
        direita.setHorizontalAlignment(SwingConstants.RIGHT);
        jT_PedidoA2.setModel(modelo);
        RowSorter<TableModel> sorter = new TableRowSorter<TableModel>(modelo);
        jT_PedidoA2.setRowSorter(sorter);
        jT_PedidoA2.getColumnModel().getColumn(0).setPreferredWidth(60);
        jT_PedidoA2.getColumnModel().getColumn(0).setCellRenderer(direita);
        jT_PedidoA2.getColumnModel().getColumn(0).setResizable(true);
        jT_PedidoA2.getColumnModel().getColumn(1).setPreferredWidth(90);
        jT_PedidoA2.getColumnModel().getColumn(1).setResizable(true);
        jT_PedidoA2.getColumnModel().getColumn(2).setPreferredWidth(100);
        jT_PedidoA2.getColumnModel().getColumn(2).setResizable(true);
        jT_PedidoA2.getColumnModel().getColumn(3).setPreferredWidth(100);
        jT_PedidoA2.getColumnModel().getColumn(3).setResizable(true);
        jT_PedidoA2.getColumnModel().getColumn(4).setPreferredWidth(180);
        jT_PedidoA2.getColumnModel().getColumn(4).setResizable(true);
        jT_PedidoA2.getColumnModel().getColumn(5).setPreferredWidth(120);
        jT_PedidoA2.getColumnModel().getColumn(5).setResizable(true);
        jT_PedidoA2.getTableHeader().setReorderingAllowed(false);
        jT_PedidoA2.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        jT_PedidoA2.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        resposta = "";
    }

    public void PreencheTabela_Expedicao() {
        DaoPedido DAOP = new DaoPedido();
        String[] colunas = new String[]{"Código ", "Status", "Data", "Cliente", "Observação", "Registro"};
        ArrayList dados;
        String b = resposta;
        dados = (ArrayList) DAOP.DashBoard_PreencheTabela_Expedicao(b);
        ModeloTabela modelo = new ModeloTabela(dados, colunas);
        DefaultTableCellRenderer esquerda = new DefaultTableCellRenderer();
        DefaultTableCellRenderer centralizado = new DefaultTableCellRenderer();
        DefaultTableCellRenderer direita = new DefaultTableCellRenderer();
        esquerda.setHorizontalAlignment(SwingConstants.LEFT);
        centralizado.setHorizontalAlignment(SwingConstants.CENTER);
        direita.setHorizontalAlignment(SwingConstants.RIGHT);
        jT_Expedicao.setModel(modelo);
        RowSorter<TableModel> sorter = new TableRowSorter<TableModel>(modelo);
        jT_Expedicao.setRowSorter(sorter);
        jT_Expedicao.getColumnModel().getColumn(0).setPreferredWidth(60);
        jT_Expedicao.getColumnModel().getColumn(0).setCellRenderer(direita);
        jT_Expedicao.getColumnModel().getColumn(0).setResizable(true);
        jT_Expedicao.getColumnModel().getColumn(1).setPreferredWidth(90);
        jT_Expedicao.getColumnModel().getColumn(1).setResizable(true);
        jT_Expedicao.getColumnModel().getColumn(2).setPreferredWidth(100);
        jT_Expedicao.getColumnModel().getColumn(2).setResizable(true);
        jT_Expedicao.getColumnModel().getColumn(3).setPreferredWidth(100);
        jT_Expedicao.getColumnModel().getColumn(3).setResizable(true);
        jT_Expedicao.getColumnModel().getColumn(4).setPreferredWidth(180);
        jT_Expedicao.getColumnModel().getColumn(4).setResizable(true);
        jT_Expedicao.getColumnModel().getColumn(5).setPreferredWidth(120);
        jT_Expedicao.getColumnModel().getColumn(5).setResizable(true);
        jT_Expedicao.getTableHeader().setReorderingAllowed(false);
        jT_Expedicao.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        jT_Expedicao.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        resposta = "";
    }

    public void PreencheTabela_UltimasEntradas() {
        DaoNota DAON = new DaoNota();
        String[] colunas = new String[]{"Cód ", "Data", "Fornecedor", "Produto", "Unidade", "Qtd"};
        ArrayList dados;
        String b = resposta;
        dados = (ArrayList) DAON.PreencheTabelaDashBoardNota(b);
        ModeloTabela modelo = new ModeloTabela(dados, colunas);
        DefaultTableCellRenderer esquerda = new DefaultTableCellRenderer();
        DefaultTableCellRenderer centralizado = new DefaultTableCellRenderer();
        DefaultTableCellRenderer direita = new DefaultTableCellRenderer();
        esquerda.setHorizontalAlignment(SwingConstants.LEFT);
        centralizado.setHorizontalAlignment(SwingConstants.CENTER);
        direita.setHorizontalAlignment(SwingConstants.RIGHT);
        jT_PedidoB2.setModel(modelo);
        RowSorter<TableModel> sorter = new TableRowSorter<TableModel>(modelo);
        jT_PedidoB2.setRowSorter(sorter);
        jT_PedidoB2.getColumnModel().getColumn(0).setPreferredWidth(40);
        jT_PedidoB2.getColumnModel().getColumn(0).setCellRenderer(direita);
        jT_PedidoB2.getColumnModel().getColumn(0).setResizable(true);
        jT_PedidoB2.getColumnModel().getColumn(1).setPreferredWidth(80);
        jT_PedidoB2.getColumnModel().getColumn(1).setResizable(true);
        jT_PedidoB2.getColumnModel().getColumn(2).setPreferredWidth(80);
        jT_PedidoB2.getColumnModel().getColumn(2).setResizable(true);
        jT_PedidoB2.getColumnModel().getColumn(3).setPreferredWidth(150);
        jT_PedidoB2.getColumnModel().getColumn(3).setResizable(true);
        jT_PedidoB2.getColumnModel().getColumn(4).setPreferredWidth(60);
        jT_PedidoB2.getColumnModel().getColumn(4).setResizable(true);
        jT_PedidoB2.getColumnModel().getColumn(5).setPreferredWidth(60);
        jT_PedidoB2.getColumnModel().getColumn(5).setResizable(true);
        jT_PedidoB2.getTableHeader().setReorderingAllowed(false);
        jT_PedidoB2.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        jT_PedidoB2.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        resposta = "";
    }

    public void PreencheTabela_UltimasSaidas() {
        DaoNota DAON = new DaoNota();
        String[] colunas = new String[]{"Cód ", "Data", "Cliente", "Produto", "Unidade", "Qtd"};
        ArrayList dados;
        String b = resposta;
        dados = (ArrayList) DAON.PreencheTabelaDashBoardExpedicao(b);
        ModeloTabela modelo = new ModeloTabela(dados, colunas);
        DefaultTableCellRenderer esquerda = new DefaultTableCellRenderer();
        DefaultTableCellRenderer centralizado = new DefaultTableCellRenderer();
        DefaultTableCellRenderer direita = new DefaultTableCellRenderer();
        esquerda.setHorizontalAlignment(SwingConstants.LEFT);
        centralizado.setHorizontalAlignment(SwingConstants.CENTER);
        direita.setHorizontalAlignment(SwingConstants.RIGHT);
        jT_Saidas.setModel(modelo);
        RowSorter<TableModel> sorter = new TableRowSorter<TableModel>(modelo);
        jT_Saidas.setRowSorter(sorter);
        jT_Saidas.getColumnModel().getColumn(0).setPreferredWidth(40);
        jT_Saidas.getColumnModel().getColumn(0).setCellRenderer(direita);
        jT_Saidas.getColumnModel().getColumn(0).setResizable(true);
        jT_Saidas.getColumnModel().getColumn(1).setPreferredWidth(80);
        jT_Saidas.getColumnModel().getColumn(1).setResizable(true);
        jT_Saidas.getColumnModel().getColumn(2).setPreferredWidth(80);
        jT_Saidas.getColumnModel().getColumn(2).setResizable(true);
        jT_Saidas.getColumnModel().getColumn(3).setPreferredWidth(150);
        jT_Saidas.getColumnModel().getColumn(3).setResizable(true);
        jT_Saidas.getColumnModel().getColumn(4).setPreferredWidth(60);
        jT_Saidas.getColumnModel().getColumn(4).setResizable(true);
        jT_Saidas.getColumnModel().getColumn(5).setPreferredWidth(60);
        jT_Saidas.getColumnModel().getColumn(5).setResizable(true);
        jT_Saidas.getTableHeader().setReorderingAllowed(false);
        jT_Saidas.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        jT_PedidoB2.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        resposta = "";
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_busca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    public static javax.swing.JLabel jLabelData;
    public static javax.swing.JLabel jLabelHora;
    public static javax.swing.JLabel jLabelIdUsuario;
    public static javax.swing.JLabel jLabelPermissao;
    public static javax.swing.JButton jLabelUsuario;
    public static javax.swing.JLabel jLabel_Password;
    private javax.swing.JLabel jLabel_principal;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    public static javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JMenuItem jMenuItem22;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel_inferior;
    public static javax.swing.JPanel jPanel_principal;
    private javax.swing.JPanel jPanel_tela1;
    private javax.swing.JPanel jPanel_tela2;
    private javax.swing.JPanel jPanel_tela3;
    private javax.swing.JPanel jPanel_tela4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTable jT_Expedicao;
    private javax.swing.JTable jT_PedidoA;
    private javax.swing.JTable jT_PedidoA2;
    private javax.swing.JTable jT_PedidoB;
    private javax.swing.JTable jT_PedidoB2;
    private javax.swing.JTable jT_Saidas;
    private javax.swing.JTable jTable_Lista;
    private javax.swing.JTextField jTextField_busca;
    // End of variables declaration//GEN-END:variables
}
