/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.Expedicao;

import ModeloBeans.BeansExpedicao;
import ModeloDao.DaoExpedicao;
import java.text.SimpleDateFormat;
import java.util.Date;
import Principal.Menu;
import java.awt.Color;
import java.text.ParseException;
import javax.swing.JOptionPane;

/**
 *
 * @author edson
 */
public class JDialogExpedicao extends javax.swing.JDialog {

    SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
    Date data = null;
    int A;
    String B, MinhaData;
    int st = 8, expedicao = 0;
    DaoExpedicao D = new DaoExpedicao();
    BeansExpedicao Bb = new BeansExpedicao();

    public JDialogExpedicao(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        corDeSelecao();
//        CarregaForm();
    }

    public void corDeSelecao() {
        jB_ag.setBackground(null);
        jB_ea.setBackground(null);
        jB_eh.setBackground(null);
        jB_en.setBackground(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jL1 = new javax.swing.JLabel();
        jL2 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jDateChooser_Data_Nota = new com.toedter.calendar.JDateChooser();
        jButton5 = new javax.swing.JButton();
        jTextField_Hora = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jB_ea = new javax.swing.JButton();
        jB_eh = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jB_en = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabelTipo = new javax.swing.JLabel();
        jLabelObs = new javax.swing.JLabel();
        jB_ag = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButton1.setText("Visualizar pedido");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Gerar nota");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Gerar protocolo");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton2, jButton3});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jL1.setText(" ");

        jL2.setText(" ");

        jButton4.setText("Data");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jDateChooser_Data_Nota.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                jDateChooser_Data_NotaHierarchyChanged(evt);
            }
        });
        jDateChooser_Data_Nota.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                jDateChooser_Data_NotaAncestorMoved(evt);
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jDateChooser_Data_NotaAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jDateChooser_Data_Nota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jDateChooser_Data_NotaMouseClicked(evt);
            }
        });
        jDateChooser_Data_Nota.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jDateChooser_Data_NotaPropertyChange(evt);
            }
        });
        jDateChooser_Data_Nota.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jDateChooser_Data_NotaKeyPressed(evt);
            }
        });
        jDateChooser_Data_Nota.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                jDateChooser_Data_NotaVetoableChange(evt);
            }
        });

        jButton5.setText("Hora");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jTextField_Hora.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_HoraFocusLost(evt);
            }
        });
        jTextField_Hora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_HoraActionPerformed(evt);
            }
        });
        jTextField_Hora.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_HoraKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_HoraKeyReleased(evt);
            }
        });

        jButton6.setText("Informações adicionais");

        jB_ea.setText("Enviado agora");
        jB_ea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_eaActionPerformed(evt);
            }
        });

        jB_eh.setText("Enviado hoje");
        jB_eh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_ehActionPerformed(evt);
            }
        });

        jLabel3.setText("Motorista");

        jLabel4.setText("Placa");

        jB_en.setText("Enviado");
        jB_en.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_enActionPerformed(evt);
            }
        });

        jButton10.setText("Finalizado");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jLabelTipo.setText("  ");
        jLabelTipo.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelObs.setText("  ");
        jLabelObs.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jB_ag.setText("Aguardando");
        jB_ag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_agActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jL1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jL2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelObs, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jDateChooser_Data_Nota, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_Hora, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jB_ea)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jB_eh)
                                .addGap(2, 2, 2)
                                .addComponent(jB_en)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jB_ag)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jB_ag, jB_eh, jB_en});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jL1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jL2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4)
                    .addComponent(jDateChooser_Data_Nota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField_Hora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabelObs))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelTipo)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB_ea)
                    .addComponent(jB_eh)
                    .addComponent(jB_en)
                    .addComponent(jB_ag))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if (jDateChooser_Data_Nota.getDate() == (null)) {
            try {
                data = formato.parse(Menu.jLabelData.getText());
                jDateChooser_Data_Nota.setDate(data);
            } catch (ParseException ex) {
                //                Logger.getLogger(MovimentoJIF.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            jDateChooser_Data_Nota.setDate(null);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jDateChooser_Data_NotaHierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_jDateChooser_Data_NotaHierarchyChanged

    }//GEN-LAST:event_jDateChooser_Data_NotaHierarchyChanged

    private void jDateChooser_Data_NotaAncestorMoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jDateChooser_Data_NotaAncestorMoved

    }//GEN-LAST:event_jDateChooser_Data_NotaAncestorMoved

    private void jDateChooser_Data_NotaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jDateChooser_Data_NotaAncestorAdded

    }//GEN-LAST:event_jDateChooser_Data_NotaAncestorAdded

    private void jDateChooser_Data_NotaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDateChooser_Data_NotaMouseClicked
        //  ManipulaData();        // TODO add your handling code here:
    }//GEN-LAST:event_jDateChooser_Data_NotaMouseClicked

    private void jDateChooser_Data_NotaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jDateChooser_Data_NotaPropertyChange
        // ManipulaData();
    }//GEN-LAST:event_jDateChooser_Data_NotaPropertyChange

    private void jDateChooser_Data_NotaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jDateChooser_Data_NotaKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            //   jComboBox_Tipo_Fornecedor.requestFocus();
        }
    }//GEN-LAST:event_jDateChooser_Data_NotaKeyPressed

    private void jDateChooser_Data_NotaVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_jDateChooser_Data_NotaVetoableChange

    }//GEN-LAST:event_jDateChooser_Data_NotaVetoableChange

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if (jTextField_Hora.getText().isEmpty()) {
            String Relogio = (Menu.jLabelHora.getText());
            //            String MenuMinhaHoraSistema = (String.format("%1$tM:%1$tS", Relogio)); /// %1$tM:%1$tS
            jTextField_Hora.setText(Relogio);
        } else {
            jTextField_Hora.setText(null);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTextField_HoraFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_HoraFocusLost
        if (jTextField_Hora.getText().isEmpty()) {
            jTextField_Hora.setText("  :  ");
        } else if (jTextField_Hora.getText().equals("  :  ")) {
            jTextField_Hora.setText("  :  ");
        } else {
            VerificaHora();
        }
    }//GEN-LAST:event_jTextField_HoraFocusLost
    public void VerificaHora() {
        String s = jTextField_Hora.getText().replace(":", "");
        if (s.length() == 1 | s.length() == 3 | s.length() == 5 | s.length() > 7) {
            jTextField_Hora.setText("");
            jTextField_Hora.requestFocus();

        }
    }

    public void AjustaMinhaHora() {
        String s = jTextField_Hora.getText().replace(":", "");
        String formatado = "";
        if (s.matches("^[0-9]*$")) {
            if (s.length() == 4) {
                formatado = s.substring(0, 2) + ":" + s.substring(2, 4);
                jTextField_Hora.setText(formatado);
            } else if (s.length() == 6) {
                formatado = s.substring(0, 2) + ":" + s.substring(2, 4) + ":" + s.substring(4, 6);
                jTextField_Hora.setText(formatado);
            } else if (s.length() < 6) {

            } else {
                jTextField_Hora.setText("");
                jTextField_Hora.requestFocus();
            }
        } else {
            jTextField_Hora.setText("");
        }
    }
    private void jTextField_HoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_HoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_HoraActionPerformed

    private void jTextField_HoraKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_HoraKeyPressed

        if (jTextField_Hora.getText().length() >= 5) {

        }
    }//GEN-LAST:event_jTextField_HoraKeyPressed

    private void jTextField_HoraKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_HoraKeyReleased
        AjustaMinhaHora();
    }//GEN-LAST:event_jTextField_HoraKeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        JDialog_Nota nota = new JDialog_Nota(null, rootPaneCheckingEnabled);
        String a = jL1.getText().replace("Nota", "").replace("Protocolo", "").replace(" ", ""), b = jL2.getText().replace("Chave", "").replace(" ", "");
        nota.recebe(a, b);
        nota.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        JDialog_Protocolo protocolo = new JDialog_Protocolo(null, rootPaneCheckingEnabled);
        String a = jL1.getText().trim().replace(" ", "").replace("Nota", "").replace("Protocolo", ""), b = jL2.getText().trim().replace("Chave", "");
        protocolo.recebe(a, b);
        protocolo.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jB_eaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_eaActionPerformed
        corDeSelecao();
        jB_ea.setBackground(Color.green);
        st = 9;
        try {
            data = formato.parse(Menu.jLabelData.getText());
            jDateChooser_Data_Nota.setDate(data);
        } catch (ParseException ex) {
            //                Logger.getLogger(MovimentoJIF.class.getName()).log(Level.SEVERE, null, ex);
        }
        String Relogio = (Menu.jLabelHora.getText());
        jTextField_Hora.setText(Relogio);

    }//GEN-LAST:event_jB_eaActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed

        if (jDateChooser_Data_Nota.getDate() == (null)) {
            MinhaData = ("");
        } else {
            data = jDateChooser_Data_Nota.getDate();
            MinhaData = (formato.format(data));
        }
        if (jLabelTipo.getText().equals("Nota")) {
            Bb.setExpData(MinhaData);
            Bb.setExpHora(jTextField_Hora.getText());
            Bb.setExpNota(jL1.getText().replace("Nota", "").replace("Protocolo", "").replace(" ", "").trim());
            Bb.setExpChave(jL2.getText().replace("Chave", "").trim());
            Bb.setExpMotorista(jTextField1.getText());
            Bb.setExpPlaca(jTextField2.getText());

            Bb.setExpStatus(st);
            Bb.setExpPedido(A);
            if (expedicao == 0) {
                D.SalvarNota(Bb);
            } else {
                Bb.setId(expedicao);
                D.AtualizarProtocolo(Bb);
            }

            Bb.setExpObservacao(jLabelObs.getText().toUpperCase());
            D.AtualizaStatusPedido(Bb);
        } else if (jLabelTipo.getText().equals("Protocolo")) {
            System.out.println("b expedicao -- " + expedicao);
            Bb.setExpData(MinhaData);
            Bb.setExpHora(jTextField_Hora.getText());
            Bb.setExpNota(jL1.getText().trim().replace("Nota", "").replace("Protocolo", "").replace(" ", "").trim());
            Bb.setExpChave(jL2.getText().replace("Chave", "").trim());
            Bb.setExpMotorista(jTextField1.getText());
            Bb.setExpPlaca(jTextField2.getText());

            Bb.setExpStatus(st);
            Bb.setExpPedido(A);
            if (expedicao == 0) {
                D.SalvarProtocolo(Bb);
            } else {
                Bb.setId(expedicao);
                D.AtualizarProtocolo(Bb);
            }

            Bb.setExpObservacao(jLabelObs.getText().toUpperCase());
            D.AtualizaStatusPedido(Bb);
        } else {
            System.out.println("c");
        }

        this.dispose();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jB_enActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_enActionPerformed
        corDeSelecao();
        jB_en.setBackground(Color.green);
        st = 9;
    }//GEN-LAST:event_jB_enActionPerformed

    private void jB_ehActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_ehActionPerformed
        corDeSelecao();
        jB_eh.setBackground(Color.green);
        st = 9;
        try {
            data = formato.parse(Menu.jLabelData.getText());
            jDateChooser_Data_Nota.setDate(data);
        } catch (ParseException ex) {
            //                Logger.getLogger(MovimentoJIF.class.getName()).log(Level.SEVERE, null, ex);
        }
        jTextField_Hora.setText(null);
    }//GEN-LAST:event_jB_ehActionPerformed

    private void jB_agActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_agActionPerformed
        corDeSelecao();
        jB_ag.setBackground(Color.green);
        st = 8;
    }//GEN-LAST:event_jB_agActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        CarregaForm();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialogExpedicao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialogExpedicao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialogExpedicao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialogExpedicao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialogExpedicao dialog = new JDialogExpedicao(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    public void Recebe(int a, String b) {
        A = a;
        B = b;
        this.setTitle("Controla expediçao " + " ( Código " + a + " )");
        if (B.equals("Aguardando")) {
            CarregaForm();
        }

    }

    public void CarregaForm() {
//        A = Integer.parseInt(jTextField1.getText());
        System.out.println("CarregaForm - A= " + A);
        DaoExpedicao d = new DaoExpedicao();
        for (BeansExpedicao ex : d.BuscaExpedicao(A)) {
            String numero = ex.getExpNota();
            String chave = ex.getExpChave();
            try {
                data = formato.parse(ex.getExpData());
                jDateChooser_Data_Nota.setDate(data);
            } catch (Exception e) {
                System.err.println("erro - " + e);
            }
            expedicao = ex.getId();
            jTextField_Hora.setText(ex.getExpHora());
            jTextField1.setText(ex.getExpMotorista());
            jTextField2.setText(ex.getExpPlaca());
            String Tipo = ex.getExpTipo();
            if (Tipo.equals("Nota")) {
                jButton2.setVisible(true);
                jButton3.setVisible(false);
                jLabelTipo.setText("Nota");
                jL1.setText("Nota " + numero);
                jL2.setText("Chave " + chave);
            } else if (Tipo.equals("Protocolo")) {
                jButton2.setVisible(false);
                jButton3.setVisible(true);
                jLabelTipo.setText("Protocolo");
                jL1.setText("Protocolo " + numero);
                jL2.setText("  ");
            } else {
                jButton2.setVisible(false);
                jButton3.setVisible(false);
                jLabelTipo.setText("Erro");

            }
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_ag;
    private javax.swing.JButton jB_ea;
    private javax.swing.JButton jB_eh;
    private javax.swing.JButton jB_en;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private com.toedter.calendar.JDateChooser jDateChooser_Data_Nota;
    public static javax.swing.JLabel jL1;
    public static javax.swing.JLabel jL2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    public static javax.swing.JLabel jLabelObs;
    public static javax.swing.JLabel jLabelTipo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField_Hora;
    // End of variables declaration//GEN-END:variables
}
