/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.Pedido;

import Controle.Janelas;
import EntradaNota.Item.JDialog_AddItem_Complemento;
import EntradaNota.Item.JDialog_AddItem_Info;
import EntradaNota.Item.JDialog_AddItem_Obs;
import ModeloBeans.BeansCliente;
import ModeloBeans.BeansItem;
import ModeloBeans.BeansPedido;
import ModeloBeans.BeansProduto;
import ModeloBeans.ModeloTabela;
import ModeloDao.DaoCliente;
import ModeloDao.DaoItem;
import ModeloDao.DaoPedido;
import Principal.Menu;
import Validacao.ValidarPedido;
import java.awt.Frame;
import java.math.BigDecimal;
import java.text.NumberFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultListModel;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.RowSorter;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author hp
 */
public class AddPedido2 extends javax.swing.JFrame {

//    ConexaoBD conex = new ConexaoBD();
    BeansPedido BEANS = new BeansPedido();
    DaoPedido DAO = new DaoPedido();
    ValidarPedido validar = new ValidarPedido();
    DefaultListModel MODELO;
    BeansItem BI = new BeansItem();
    DaoItem DI = new DaoItem();
    int ModoItem = 1;
    Frame tela = null;
    JDialog_AddItem_Info info = new JDialog_AddItem_Info(tela, rootPaneCheckingEnabled);
    JDialog_AddItem_Complemento complemento = new JDialog_AddItem_Complemento(tela, rootPaneCheckingEnabled);

    String resposta = "", observacao = "", MinhaData, UltimoIdNota = "";
    String complemento_texto = "", selecao, produto, item_id_nota, Minha_Id = "";
    SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
    Date data = null;
    String item_id_campo;
    int ModoDeSalvar = 0;

    /**
     * Creates new form AddPedido2
     */
    public AddPedido2() {
        initComponents();
        item_id_campo = "item_id_pedido";
        MODELO = new DefaultListModel();
        jList1.setModel(MODELO);
//        PreencherProduto();
        jTextField_buscar.setEnabled(false);
        jButton6.setEnabled(false);
        jLabel1.setEnabled(false);
        OcultaInicializacao();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jDateChooser_Data_Nota = new com.toedter.calendar.JDateChooser();
        jTextField_Hora = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jC_Clie = new javax.swing.JComboBox<>();
        jC_Clie_Id = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel_Total = new javax.swing.JLabel();
        jLabel_observacao_pedido = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jScrollPane_lista = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jTextField_buscar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jComboBox_prod_id_3 = new javax.swing.JComboBox<>();
        jTextField_qtd = new javax.swing.JTextField();
        jComboBox_prod_id_1 = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_item = new javax.swing.JTable();
        jButton_add = new javax.swing.JButton();
        jButton_com = new javax.swing.JButton();
        jButton_lim = new javax.swing.JButton();
        jButton_alt = new javax.swing.JButton();
        jButton_del = new javax.swing.JButton();
        jLabel_complemento = new javax.swing.JLabel();
        jLabel_qtd = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jDateChooser_Data_Nota.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                jDateChooser_Data_NotaHierarchyChanged(evt);
            }
        });
        jDateChooser_Data_Nota.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                jDateChooser_Data_NotaAncestorMoved(evt);
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jDateChooser_Data_NotaAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jDateChooser_Data_Nota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jDateChooser_Data_NotaMouseClicked(evt);
            }
        });
        jDateChooser_Data_Nota.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jDateChooser_Data_NotaPropertyChange(evt);
            }
        });
        jDateChooser_Data_Nota.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jDateChooser_Data_NotaKeyPressed(evt);
            }
        });
        jDateChooser_Data_Nota.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                jDateChooser_Data_NotaVetoableChange(evt);
            }
        });

        jTextField_Hora.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_HoraFocusLost(evt);
            }
        });
        jTextField_Hora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_HoraActionPerformed(evt);
            }
        });
        jTextField_Hora.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_HoraKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_HoraKeyReleased(evt);
            }
        });

        jButton1.setText("Data");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Hora");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setText("Cliente : ");

        jC_Clie.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jC_Clie.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jC_ClieItemStateChanged(evt);
            }
        });
        jC_Clie.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jC_ClieKeyPressed(evt);
            }
        });

        jC_Clie_Id.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton3.setText("Processar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Total");

        jLabel_Total.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        jLabel_Total.setForeground(new java.awt.Color(255, 0, 0));
        jLabel_Total.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Total.setText("0");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_Total, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_Total, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jC_Clie, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jDateChooser_Data_Nota, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_Hora, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(2, 2, 2)
                        .addComponent(jC_Clie_Id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_observacao_pedido, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jC_Clie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jC_Clie_Id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(jDateChooser_Data_Nota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextField_Hora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel_observacao_pedido)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButton5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton5.setText("Informações adicionais");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(51, 51, 255));
        jButton6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Finalizar pedido");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 51, 51));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText(" ");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 51, 51));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("...");

        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));

        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jList1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "ar", "fogo", "vento", "agua" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane_lista.setViewportView(jList1);

        jLayeredPane1.add(jScrollPane_lista, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 22, 390, 80));

        jTextField_buscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_buscarKeyReleased(evt);
            }
        });
        jLayeredPane1.add(jTextField_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 0, 380, -1));

        jLabel1.setText("Produto :");
        jLayeredPane1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 3, -1, -1));

        jComboBox_prod_id_3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox_prod_id_3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox_prod_id_3ItemStateChanged(evt);
            }
        });
        jLayeredPane1.add(jComboBox_prod_id_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(625, 0, -1, -1));

        jTextField_qtd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_qtdKeyReleased(evt);
            }
        });
        jLayeredPane1.add(jTextField_qtd, new org.netbeans.lib.awtextra.AbsoluteConstraints(487, 0, 74, -1));

        jComboBox_prod_id_1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox_prod_id_1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox_prod_id_1ItemStateChanged(evt);
            }
        });
        jLayeredPane1.add(jComboBox_prod_id_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(571, 0, 48, -1));

        jTable_item.setAutoCreateRowSorter(true);
        jTable_item.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable_item.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_itemMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTable_itemMouseEntered(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_item);

        jButton_add.setText("Adicionar");
        jButton_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_addActionPerformed(evt);
            }
        });
        jButton_add.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton_addKeyPressed(evt);
            }
        });

        jButton_com.setText("Complemento");
        jButton_com.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_comActionPerformed(evt);
            }
        });

        jButton_lim.setText("Limpar");
        jButton_lim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_limActionPerformed(evt);
            }
        });

        jButton_alt.setText("Alterar");
        jButton_alt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_altActionPerformed(evt);
            }
        });

        jButton_del.setText("Deletar");
        jButton_del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_delActionPerformed(evt);
            }
        });

        jLabel_complemento.setText(" ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButton_add)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_alt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_del)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_com)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_lim)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_complemento, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton_add, jButton_alt, jButton_com, jButton_del, jButton_lim});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_add)
                    .addComponent(jButton_com)
                    .addComponent(jButton_lim)
                    .addComponent(jButton_alt)
                    .addComponent(jButton_del)
                    .addComponent(jLabel_complemento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLayeredPane1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-5, 33, 760, 280));

        jLabel_qtd.setText("Qtd:");
        jLayeredPane1.add(jLabel_qtd, new org.netbeans.lib.awtextra.AbsoluteConstraints(461, 3, -1, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton6))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 399, Short.MAX_VALUE)
                    .addComponent(jLabel5)
                    .addGap(0, 399, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton5)
                        .addComponent(jLabel7))
                    .addComponent(jButton6))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel5)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jDateChooser_Data_NotaHierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_jDateChooser_Data_NotaHierarchyChanged

    }//GEN-LAST:event_jDateChooser_Data_NotaHierarchyChanged

    private void jDateChooser_Data_NotaAncestorMoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jDateChooser_Data_NotaAncestorMoved

    }//GEN-LAST:event_jDateChooser_Data_NotaAncestorMoved

    private void jDateChooser_Data_NotaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jDateChooser_Data_NotaAncestorAdded

    }//GEN-LAST:event_jDateChooser_Data_NotaAncestorAdded

    private void jDateChooser_Data_NotaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDateChooser_Data_NotaMouseClicked
        //  ManipulaData();        // TODO add your handling code here:
    }//GEN-LAST:event_jDateChooser_Data_NotaMouseClicked

    private void jDateChooser_Data_NotaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jDateChooser_Data_NotaPropertyChange
        // ManipulaData();
    }//GEN-LAST:event_jDateChooser_Data_NotaPropertyChange

    private void jDateChooser_Data_NotaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jDateChooser_Data_NotaKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            //   jComboBox_Tipo_Fornecedor.requestFocus();
        }
    }//GEN-LAST:event_jDateChooser_Data_NotaKeyPressed

    private void jDateChooser_Data_NotaVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_jDateChooser_Data_NotaVetoableChange

    }//GEN-LAST:event_jDateChooser_Data_NotaVetoableChange

    private void jTextField_HoraFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_HoraFocusLost
        if (jTextField_Hora.getText().isEmpty()) {
            jTextField_Hora.setText("  :  ");
        } else if (jTextField_Hora.getText().equals("  :  ")) {
            jTextField_Hora.setText("  :  ");
        } else {
            VerificaHora();
        }
    }//GEN-LAST:event_jTextField_HoraFocusLost

    private void jTextField_HoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_HoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_HoraActionPerformed

    private void jTextField_HoraKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_HoraKeyPressed

        if (jTextField_Hora.getText().length() >= 5) {

        }
    }//GEN-LAST:event_jTextField_HoraKeyPressed

    private void jTextField_HoraKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_HoraKeyReleased
        AjustaMinhaHora();
    }//GEN-LAST:event_jTextField_HoraKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (jDateChooser_Data_Nota.getDate() == (null)) {
            try {
                data = formato.parse(Menu.jLabelData.getText());
                jDateChooser_Data_Nota.setDate(data);
            } catch (ParseException ex) {
                //                Logger.getLogger(MovimentoJIF.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            jDateChooser_Data_Nota.setDate(null);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (jTextField_Hora.getText().isEmpty()) {
            String Relogio = (Menu.jLabelHora.getText());
            //            String MenuMinhaHoraSistema = (String.format("%1$tM:%1$tS", Relogio)); /// %1$tM:%1$tS
            jTextField_Hora.setText(Relogio);
        } else {
            jTextField_Hora.setText(null);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jC_ClieItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jC_ClieItemStateChanged
        try {
            jC_Clie_Id.setSelectedIndex(jC_Clie.getSelectedIndex());
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jC_ClieItemStateChanged

    private void jC_ClieKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jC_ClieKeyPressed
        if (evt.getKeyCode() == evt.VK_F5) {
            PreencherCliente();
        }
    }//GEN-LAST:event_jC_ClieKeyPressed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        BloqueiaCampos2();
        jLabel5.setText("Nota em processamento ");
        Processar();
        PreencherTotal();
        jButton6.setEnabled(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        jComboBox_prod_id_3.setSelectedIndex(jList1.getSelectedIndex());
        jTextField_buscar.setText(jList1.getSelectedValue());
        jScrollPane_lista.setVisible(false);
        jList1.setVisible(false);
        jTextField_qtd.setEnabled(true);
        jTextField_qtd.setVisible(true);
        jLabel_qtd.setVisible(true);
        jTextField_qtd.requestFocus();
        jTextField_buscar.setEditable(false);
    }//GEN-LAST:event_jList1MouseClicked

    private void jTextField_buscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_buscarKeyReleased
        resposta = jTextField_buscar.getText();

        if (evt.getKeyCode() == evt.VK_F1) {
            String n = "" + jComboBox_prod_id_1.getSelectedItem();
            info.RecebeId(n);
            info.setVisible(true);
        }

        if (resposta.length() > 1) {
            PreencherProduto();

        }
        if (evt.getKeyCode() == evt.VK_BACK_SPACE) {
            if (resposta.length() < 1) {
                jScrollPane_lista.setVisible(false);

            }

            int a = jComboBox_prod_id_3.getSelectedIndex();
            if (a == 0) {
                System.out.println("--- identificação => " + a);
                jTextField_buscar.setEditable(true);
                jTextField_qtd.setEnabled(false);
            }
            //            System.out.println("--- identificação => " + a);
        }
        jTextField_buscar.requestFocus();
    }//GEN-LAST:event_jTextField_buscarKeyReleased

    private void jComboBox_prod_id_3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox_prod_id_3ItemStateChanged

    }//GEN-LAST:event_jComboBox_prod_id_3ItemStateChanged

    private void jTextField_qtdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_qtdKeyReleased
        if (evt.getKeyCode() == evt.VK_ENTER) {
            if (jTextField_qtd.getText().isEmpty()) {
            } else {
                if (jButton_alt.isEnabled()) {
                    jButton_alt.setEnabled(true);
                    jButton_alt.requestFocus();
                } else {
                    BotoesMostra();
                    jButton_add.setEnabled(true);
                    jButton_add.requestFocus();
                    jButton_com.setEnabled(true);
                }
            }
        }
        String s = jTextField_qtd.getText();
        if (s.matches("^[0-9,]*$")) {
        } else {
            jTextField_qtd.setText("");
        }
        if (evt.getKeyCode() == evt.VK_F1) {
            complemento.setVisible(true);
        }
    }//GEN-LAST:event_jTextField_qtdKeyReleased

    private void jComboBox_prod_id_1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox_prod_id_1ItemStateChanged
        try {
            //            jComboBox_prod.setSelectedIndex(jComboBox_prod_id_1.getSelectedIndex());
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jComboBox_prod_id_1ItemStateChanged

    private void jTable_itemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_itemMouseClicked
        jScrollPane_lista.setVisible(false);
        if (evt.getClickCount() == 2) {
            selecao = "" + jTable_item.getValueAt(jTable_item.getSelectedRow(), 0);
            produto = "" + jTable_item.getValueAt(jTable_item.getSelectedRow(), 1);
            System.out.println("jTable1-- " + selecao);
            jButton_alt.setEnabled(true);
            jButton_del.setEnabled(true);
            jButton_com.setEnabled(true);
            BotoesMostra();
            BuscaDados();
            jLabel_qtd.setVisible(true);
            jTextField_qtd.setVisible(true);
            jTextField_buscar.requestFocus();
        }
    }//GEN-LAST:event_jTable_itemMouseClicked

    private void jTable_itemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_itemMouseEntered

    }//GEN-LAST:event_jTable_itemMouseEntered

    private void jButton_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_addActionPerformed
        if (jTextField_qtd.getText().trim().isEmpty()) {
            jTextField_qtd.requestFocus();
        } else {
            Processar_item();
        }
    }//GEN-LAST:event_jButton_addActionPerformed

    private void jButton_addKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton_addKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            jButton_add.doClick();
        }
    }//GEN-LAST:event_jButton_addKeyPressed

    private void jButton_comActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_comActionPerformed
        String codigo = (String) jComboBox_prod_id_3.getSelectedItem();
        complemento.RecebeId(codigo);
        complemento.jTextField_complemento.setText(jLabel_complemento.getText());
        complemento.setVisible(true);
    }//GEN-LAST:event_jButton_comActionPerformed

    private void jButton_limActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_limActionPerformed
        jTextField_buscar.setText("");
        jTextField_qtd.setText("");
        jLabel_complemento.setText("");
        OcultaInicializacao();
    }//GEN-LAST:event_jButton_limActionPerformed

    private void jButton_altActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_altActionPerformed
        if (jTextField_qtd.getText().trim().isEmpty()) {
            jTextField_qtd.requestFocus();
        } else {
            ModoItem = 2;
            Processar_item();

        }
    }//GEN-LAST:event_jButton_altActionPerformed

    private void jButton_delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_delActionPerformed
        if (jTextField_qtd.getText().trim().isEmpty()) {
            jTextField_qtd.requestFocus();
        } else {
            ModoItem = 3;
            Processar_item();

        }
    }//GEN-LAST:event_jButton_delActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        JDialog_AddItem_Obs AddItem_Obs = new JDialog_AddItem_Obs(this, rootPaneCheckingEnabled);
        AddItem_Obs.RecebeObs(jLabel_observacao_pedido.getText());
        AddItem_Obs.setVisible(true);
        jLabel_observacao_pedido.setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

        jLabel5.setText(" ");
        jC_Clie.requestFocus();
        Validar();
        BloqueiaCampos1();
//        OcultaInicializacao();
        Menu.jLabelUsuario.doClick();
        LimpaTudo();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing

        AoFechar();//        LimpaTudo();
    }//GEN-LAST:event_formWindowClosing
    public void LimpaTudo() {
        jDateChooser_Data_Nota.setDate(null);
        jTextField_Hora.setText(null);

        observacao = "";
        UltimoIdNota = "";
        jLabel_observacao_pedido.setText("");
        PreencherCliente();
        ArrayList dados = new ArrayList();
        String[] colunas = new String[]{};
        ModeloTabela modelo = new ModeloTabela(dados, colunas);
        jTable_item.setModel(modelo);

        ModoDeSalvar = 0;
        jTextField_buscar.setEnabled(false);
        jLabel1.setEnabled(false);
        this.dispose();

    }

    public void AoFechar() {
        DesbloqueiaCampos2();
        jTextField_buscar.setEnabled(false);
        jLabel1.setEnabled(false);
        jButton6.setEnabled(false);
        Menu.jLabelUsuario.doClick();
        LimpaTudo();

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddPedido2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddPedido2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddPedido2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddPedido2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddPedido2().setVisible(true);
            }
        });
    }

    //  cabecalho
    public void VerificaHora() {
        String s = jTextField_Hora.getText().replace(":", "");
        if (s.length() == 1 | s.length() == 3 | s.length() == 5 | s.length() > 7) {
            jTextField_Hora.setText("");
            jTextField_Hora.requestFocus();

        }
    }

    public void AjustaMinhaHora() {
        String s = jTextField_Hora.getText().replace(":", "");
        String formatado = "";
        if (s.matches("^[0-9]*$")) {
            if (s.length() == 4) {
                formatado = s.substring(0, 2) + ":" + s.substring(2, 4);
                jTextField_Hora.setText(formatado);
            } else if (s.length() == 6) {
                formatado = s.substring(0, 2) + ":" + s.substring(2, 4) + ":" + s.substring(4, 6);
                jTextField_Hora.setText(formatado);
            } else if (s.length() < 6) {

            } else {
                jTextField_Hora.setText("");
                jTextField_Hora.requestFocus();
            }
        } else {
            jTextField_Hora.setText("");
        }
    }

    public void PreencherCliente() {
        jC_Clie.removeAllItems();
        jC_Clie_Id.removeAllItems();
        DaoCliente C = new DaoCliente();
        for (BeansCliente u : C.PreencheCliente()) {
            jC_Clie.addItem(u.getCliente_nome());
            jC_Clie_Id.addItem(String.valueOf(u.getCliente_id()));
        }
    }

    public void PreencherCliente2(int A) {
        int a = A;
        jC_Clie.removeAllItems();
        jC_Clie_Id.removeAllItems();
        resposta = "";
        DaoCliente C = new DaoCliente();
        for (BeansCliente u : C.PreencheCliente2(a)) {
            jC_Clie.addItem(u.getCliente_nome());
            jC_Clie_Id.addItem(String.valueOf(u.getCliente_id()));
        }
    }

    public void BloqueiaCampos1() {
        jTable_item.setEnabled(false);

        jButton5.setEnabled(false);
        jButton6.setEnabled(false);
        jPanel2.setEnabled(false);
        DesbloqueiaCampos2();
        ArrayList dados = new ArrayList();
        String[] colunas = new String[]{};
        ModeloTabela modelo = new ModeloTabela(dados, colunas);
        jTable_item.setModel(modelo);
        jLabel_Total.setText("0");
    }

    public void DesbloqueiaCampos1() {
        jTable_item.setEnabled(true);

        jButton5.setEnabled(true);
        jButton6.setEnabled(true);
        jPanel2.setEnabled(true);
    }

    public void BloqueiaCampos2() {
        jC_Clie.setEnabled(false);
        jButton1.setEnabled(false);
        jButton2.setEnabled(false);
        jButton3.setEnabled(false);
        jDateChooser_Data_Nota.setEnabled(false);
        jTextField_Hora.setEnabled(false);
        jLabel1.setEnabled(false);
        jLabel2.setEnabled(false);
        jTextField_buscar.setEnabled(true);
        jLabel1.setEnabled(true);
        DesbloqueiaCampos1();
    }

    public void DesbloqueiaCampos2() {
        jC_Clie.setEnabled(true);
        jButton1.setEnabled(true);
        jButton2.setEnabled(true);
        jButton3.setEnabled(true);
        jDateChooser_Data_Nota.setEnabled(true);
        jTextField_Hora.setEnabled(true);

        jLabel1.setEnabled(true);
        jLabel2.setEnabled(true);

    }

    public void Processar() {

        BEANS.setPedido_id_cliente(Integer.parseInt((String) jC_Clie_Id.getSelectedItem()));
        if (jDateChooser_Data_Nota.getDate() == (null)) {
            MinhaData = ("");
        } else {
            data = jDateChooser_Data_Nota.getDate();
            MinhaData = (formato.format(data));
        }
        BEANS.setPedido_data(MinhaData);
        BEANS.setPedido_hora(jTextField_Hora.getText());

        String total = jLabel_Total.getText();
        total = total.replace(",", ".").replace("R$ ", "").replace("R$", "").trim();
        BEANS.setPedido_total(Double.parseDouble(total));
        BEANS.setPedido_status(4);
        try {
            BEANS.setPedido_id_usuario(Integer.parseInt(Menu.jLabelIdUsuario.getText()));
        } catch (Exception e) {
            BEANS.setPedido_id_usuario(1);
        }
        observacao = jLabel_observacao_pedido.getText();
        BEANS.setPedido_observacao(observacao);

        if (ModoDeSalvar == 1) {
            BEANS.setId_pedido(Integer.parseInt(UltimoIdNota));
            DAO.ProcessarAlteracao(BEANS);
        } else {
            DAO.Processar(BEANS);
            CarregaUltimo();
        }
//        ListaNota.jMenuItem4.doClick();
        PreencheTabela();
        jTextField_buscar.requestFocus();
    }

    public void CarregaUltimo() {
        String A = DAO.CarregaUltimo();
        UltimoIdNota = A;
    }

    public void PreencherTotal() {
        DaoItem DaoI = new DaoItem();
        String A = DaoI.PreencherTotal(UltimoIdNota, item_id_campo);
        jLabel_Total.setText(A);
    }

    // corpo
    public void PreencheTabela() {
        String item_id_nota = UltimoIdNota;
        ArrayList dados;
        String[] colunas = new String[]{"Codigo ", "Produto", "UN", "Valor Un", "Quantidade", "Sub total"};
        DaoItem DaoI = new DaoItem();
        dados = (ArrayList) DaoI.PreencheTabela(item_id_nota, item_id_campo);
        ModeloTabela modelo = new ModeloTabela(dados, colunas);
        jTable_item.setModel(modelo);
        RowSorter<TableModel> sorter = new TableRowSorter<TableModel>(modelo);
        jTable_item.setRowSorter(sorter);
        jTable_item.getColumnModel().getColumn(0).setPreferredWidth(60);
        jTable_item.getColumnModel().getColumn(0).setResizable(true);
        jTable_item.getColumnModel().getColumn(1).setPreferredWidth(300);
        jTable_item.getColumnModel().getColumn(1).setResizable(true);
        jTable_item.getColumnModel().getColumn(2).setPreferredWidth(40);
        jTable_item.getColumnModel().getColumn(2).setResizable(true);
        jTable_item.getColumnModel().getColumn(3).setPreferredWidth(100);
        jTable_item.getColumnModel().getColumn(3).setResizable(true);
        jTable_item.getColumnModel().getColumn(4).setPreferredWidth(100);
        jTable_item.getColumnModel().getColumn(4).setResizable(true);
        jTable_item.getColumnModel().getColumn(5).setPreferredWidth(120);
        jTable_item.getColumnModel().getColumn(5).setResizable(true);
        jTable_item.getTableHeader().setReorderingAllowed(false);
        jTable_item.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        jTable_item.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        PreencherTotal();
    }

    public void PreencherProduto() {
        MODELO.removeAllElements();
        jComboBox_prod_id_3.removeAllItems();
        jComboBox_prod_id_1.removeAllItems();
        DaoItem DaoI = new DaoItem();
        for (BeansProduto B : DaoI.PreencheListaA(resposta)) {
            jComboBox_prod_id_3.addItem(String.valueOf(B.getProduto_id()));
            jComboBox_prod_id_1.addItem(String.valueOf(B.getProduto_id()));
            MODELO.addElement(B.getProduto_nome());
            jList1.setModel(MODELO);
            jScrollPane_lista.setVisible(true);
            jList1.setVisible(true);
        }
    }

    public void BotoesEsconde() {
        jButton_add.setVisible(false);
        jButton_alt.setVisible(false);
        jButton_com.setVisible(false);
        jButton_del.setVisible(false);
        jButton_lim.setVisible(false);
    }

    public void BotoesMostra() {
        jButton_add.setVisible(true);
        jButton_alt.setVisible(true);
        jButton_com.setVisible(true);
        jButton_del.setVisible(true);
        jButton_lim.setVisible(true);
    }

    public void BotoesBloqueia() {
        jButton_add.setEnabled(false);
        jButton_alt.setEnabled(false);
        jButton_com.setEnabled(false);
        jButton_del.setEnabled(false);

    }

    public void BotoesDesbloqueia() {
        jButton_add.setEnabled(true);
        jButton_com.setEnabled(true);

    }

    public void BuscaDados() {

        DaoItem I = new DaoItem();
        for (BeansItem u : I.BuscaDados(selecao)) {
            Minha_Id = String.valueOf(u.getId());
            jTextField_qtd.setText(u.getP_qtd());
            jComboBox_prod_id_1.setSelectedItem(u.getT_produto_id());
            jTextField_buscar.setText(u.getP_descricao());
        }
    }

    public void Processar_item() {
        item_id_nota = UltimoIdNota;
        complemento_texto = jLabel_complemento.getText();
        complemento_texto = complemento_texto.toUpperCase();
        BI.setT_produto_id(Integer.parseInt((String) jComboBox_prod_id_3.getSelectedItem()));
        BI.setItem_id_pedido(Integer.parseInt((String) item_id_nota));
        BI.setT_complemento(complemento_texto);
        String qtd = jTextField_qtd.getText();
        qtd = qtd.replace(".", "").replace(",", ".").replace(",,", "").replace(",,,", "").replace(",,,,", "");
        BI.setT_qtd(Double.parseDouble(qtd));

        if (ModoItem == 1) {
            BI.setT_item_st(1);
            DI.Salvar(BI);
        } else if (ModoItem == 3) {
            BI.setT_item_st(3);
            BI.setId(Integer.parseInt((String) Minha_Id));
            DI.Deletar(BI);
        } else {
            BI.setT_item_st(1);
            BI.setId(Integer.parseInt((String) Minha_Id));
            DI.Alterar(BI);
        }
        ModoItem = 1;
        PreencheTabela();
        jTextField_buscar.setText("");
        jTextField_qtd.setText("");
        jLabel_complemento.setText("");
        OcultaInicializacao();
    }

    public void OcultaInicializacao() {
        jC_Clie_Id.setVisible(false);
        jComboBox_prod_id_3.setVisible(false);
        jComboBox_prod_id_1.setVisible(false);
        jScrollPane_lista.setVisible(false);
        BotoesEsconde();
        jLabel_qtd.setVisible(false);
        jTextField_qtd.setVisible(false);
        BotoesBloqueia();
        jTextField_buscar.setEditable(true);
        jTextField_buscar.requestFocus();

    }

    // rodape
    public void Validar() {
        BEANS.setId_pedido(Integer.parseInt(UltimoIdNota));
        double d = Double.parseDouble(jLabel_Total.getText().replace("R$", "").replace(".", "").replace(",", "."));
        BEANS.setPedido_total(d);
        DAO.ProcessarTotal(BEANS);

        observacao = jLabel_observacao_pedido.getText();
        BEANS.setPedido_observacao(observacao);
        DAO.AtualizaObs(BEANS);

        BEANS.setId_pedido(Integer.parseInt(UltimoIdNota));
        validar.Validar(BEANS);
        validar.LimpaValidar(BEANS);
        VerificaValidacao();
    }

    public void VerificaValidacao() {
        validar.VerificaValidacao(UltimoIdNota);
    }

    public void CarregaPedido(int a) {
        LimpaTudo();
        if (a == 0) {
            ModoDeSalvar = 0;
            PreencherCliente();
              this.setTitle("Novo Pedido  ");
        } else {
            for (BeansPedido p : DAO.CarregaPedido(a)) {
                try {
                    data = formato.parse(String.valueOf(p.getPedido_data()));
                } catch (Exception e) {
                    data = null;
                    System.err.println("CarregaPedido - erro ao converter data - " + e);
                }
                UltimoIdNota = String.valueOf(p.getId_pedido());
                jDateChooser_Data_Nota.setDate(data);
                jTextField_Hora.setText(p.getPedido_hora());
                jLabel_Total.setText(DAO.Total(p.getPedido_total()));
                int c = p.getPedido_id_cliente();
                PreencherCliente2(c);
                ModoDeSalvar = 1;
                 this.setTitle("Editar Pedido " + " ( Código " + UltimoIdNota + " )");
            }
            System.out.println("a -- " + a);
        }

//        jC_Clie.removeAllItems();
//        jC_Clie_Id.removeAllItems();
//        DaoCliente C = new DaoCliente();
//        for (BeansCliente u : C.PreencheCliente()) {
//            jC_Clie.addItem(u.getCliente_nome());
//            jC_Clie_Id.addItem(String.valueOf(u.getCliente_id()));
//        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton_add;
    private javax.swing.JButton jButton_alt;
    private javax.swing.JButton jButton_com;
    private javax.swing.JButton jButton_del;
    private javax.swing.JButton jButton_lim;
    private javax.swing.JComboBox<String> jC_Clie;
    private javax.swing.JComboBox<String> jC_Clie_Id;
    private javax.swing.JComboBox<String> jComboBox_prod_id_1;
    private javax.swing.JComboBox<String> jComboBox_prod_id_3;
    private com.toedter.calendar.JDateChooser jDateChooser_Data_Nota;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel_Total;
    public static javax.swing.JLabel jLabel_complemento;
    public static javax.swing.JLabel jLabel_observacao_pedido;
    private javax.swing.JLabel jLabel_qtd;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane_lista;
    private javax.swing.JTable jTable_item;
    private javax.swing.JTextField jTextField_Hora;
    public static javax.swing.JTextField jTextField_buscar;
    private javax.swing.JTextField jTextField_qtd;
    // End of variables declaration//GEN-END:variables
}
