/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.Cliente;

import ConectaBanco.ConexaoBD;
import Controle.ControleCliente;
import ModeloBeans.BeansCliente;
import ModeloDao.DaoCliente;
import Principal.Menu;
import java.awt.Color;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author edson
 */
public class EditCliente extends javax.swing.JDialog {
// Chama conexao

    ConexaoBD conex = new ConexaoBD();

// chama benas e dao
    BeansCliente BEANS = new BeansCliente();
    DaoCliente DAO = new DaoCliente();
    ControleCliente control = new ControleCliente();
// Campos internos
    int id_referencia, rid;
    String cnpj, cep, telefone, Rid;

    /**
     * Creates new form AddUsuario
     */
    public EditCliente(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton_Salvar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jTextFieldDescricao = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jFormattedTextFieldCnpj = new javax.swing.JFormattedTextField();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jFormattedTextFieldInscricao = new javax.swing.JFormattedTextField();
        jFormattedTextFieldTelefone = new javax.swing.JFormattedTextField();
        jButton3 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jTextFieldEndereco = new javax.swing.JTextField();
        jTextFieldNumero = new javax.swing.JTextField();
        jTextFieldComplemento = new javax.swing.JTextField();
        jTextFieldBairro = new javax.swing.JTextField();
        jTextFieldCidade = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jFormattedTextFieldCep = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_Observacao = new javax.swing.JTextArea();
        jLabel24 = new javax.swing.JLabel();
        jLabelExibirInformacoes = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Editar cliente");
        setResizable(false);

        jPanel1.setToolTipText("");

        jButton_Salvar.setBackground(new java.awt.Color(0, 204, 0));
        jButton_Salvar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton_Salvar.setText("Salvar alteração");
        jButton_Salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SalvarActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("Nome:");

        jLabel14.setText("Descrição:");

        jLabel15.setText("* CNPJ:");
        jLabel15.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel15MouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel15MouseMoved(evt);
            }
        });
        jLabel15.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jLabel15FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jLabel15FocusLost(evt);
            }
        });
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });

        jTextFieldNome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldNomeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldNomeFocusLost(evt);
            }
        });
        jTextFieldNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeActionPerformed(evt);
            }
        });
        jTextFieldNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldNomeKeyPressed(evt);
            }
        });

        jTextFieldDescricao.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldDescricaoFocusLost(evt);
            }
        });
        jTextFieldDescricao.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jTextFieldDescricaoInputMethodTextChanged(evt);
            }
        });
        jTextFieldDescricao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldDescricaoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldDescricaoKeyReleased(evt);
            }
        });

        jLabel16.setText("*Telefone:");
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });

        jLabel22.setText("Insc. Est.:");

        try {
            jFormattedTextFieldCnpj.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldCnpj.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jFormattedTextFieldCnpjFocusLost(evt);
            }
        });
        jFormattedTextFieldCnpj.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jFormattedTextFieldCnpjKeyPressed(evt);
            }
        });

        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        try {
            jFormattedTextFieldInscricao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###.###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldInscricao.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jFormattedTextFieldInscricaoFocusLost(evt);
            }
        });
        jFormattedTextFieldInscricao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jFormattedTextFieldInscricaoKeyPressed(evt);
            }
        });

        try {
            jFormattedTextFieldTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldTelefone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jFormattedTextFieldTelefoneFocusLost(evt);
            }
        });
        jFormattedTextFieldTelefone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jFormattedTextFieldTelefoneKeyPressed(evt);
            }
        });

        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel16))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextFieldCnpj)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jFormattedTextFieldTelefone)
                    .addComponent(jFormattedTextFieldInscricao, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jButton3))
                .addGap(22, 22, 22))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel15)
                                .addComponent(jFormattedTextFieldCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jFormattedTextFieldInscricao)
                                .addComponent(jLabel22))
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14)
                        .addComponent(jTextFieldDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel16)
                        .addComponent(jFormattedTextFieldTelefone)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel17.setText("Endereço:");

        jLabel18.setText("No:");

        jLabel19.setText("*Cep:");
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
        });

        jLabel20.setText("Complemento:");

        jLabel21.setText("Bairro:");

        jLabel23.setText("Cidade:");

        jTextFieldEndereco.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldEnderecoFocusLost(evt);
            }
        });
        jTextFieldEndereco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldEnderecoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldEnderecoKeyReleased(evt);
            }
        });

        jTextFieldNumero.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldNumeroFocusLost(evt);
            }
        });
        jTextFieldNumero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldNumeroKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldNumeroKeyReleased(evt);
            }
        });

        jTextFieldComplemento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldComplementoFocusLost(evt);
            }
        });
        jTextFieldComplemento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldComplementoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldComplementoKeyReleased(evt);
            }
        });

        jTextFieldBairro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldBairroFocusLost(evt);
            }
        });
        jTextFieldBairro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldBairroKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldBairroKeyReleased(evt);
            }
        });

        jTextFieldCidade.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldCidadeFocusLost(evt);
            }
        });
        jTextFieldCidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldCidadeKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldCidadeKeyReleased(evt);
            }
        });

        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        try {
            jFormattedTextFieldCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldCep.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jFormattedTextFieldCepFocusLost(evt);
            }
        });
        jFormattedTextFieldCep.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jFormattedTextFieldCepKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jTextFieldEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 603, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jFormattedTextFieldCep, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(26, 26, 26))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(jTextFieldEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20)
                            .addComponent(jTextFieldComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jFormattedTextFieldCep)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jLabel23)
                    .addComponent(jTextFieldBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jTextArea_Observacao.setColumns(20);
        jTextArea_Observacao.setLineWrap(true);
        jTextArea_Observacao.setRows(5);
        jTextArea_Observacao.setToolTipText("");
        jTextArea_Observacao.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextArea_Observacao.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextArea_ObservacaoFocusLost(evt);
            }
        });
        jTextArea_Observacao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextArea_ObservacaoKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTextArea_Observacao);

        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("Informação adicional");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabelExibirInformacoes.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelExibirInformacoes.setForeground(new java.awt.Color(255, 0, 0));
        jLabelExibirInformacoes.setText(" ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(158, Short.MAX_VALUE)
                .addComponent(jLabelExibirInformacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton_Salvar))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(375, Short.MAX_VALUE)
                .addComponent(jLabelExibirInformacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jButton_Salvar)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_SalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SalvarActionPerformed
        evento_Verifica();
    }//GEN-LAST:event_jButton_SalvarActionPerformed

    private void jLabel15MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseDragged
        // jLabel15.setBackground(Color.yellow);
        //        System.out.println("RECEBI O FOCO3");
        //        jLabel15.setForeground(Color.yellow);
    }//GEN-LAST:event_jLabel15MouseDragged

    private void jLabel15MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseMoved
        //       jLabel15.setBackground(Color.yellow);
        //        System.out.println("RECEBI O FOCO2");
        //         jLabel15.setForeground(Color.yellow);
    }//GEN-LAST:event_jLabel15MouseMoved

    private void jLabel15FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jLabel15FocusGained
        // jLabel15.setBackground(null);
        // System.out.println("RECEBI O FOCO1");
    }//GEN-LAST:event_jLabel15FocusGained

    private void jLabel15FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jLabel15FocusLost
        jLabel15.setBackground(Color.green);
    }//GEN-LAST:event_jLabel15FocusLost

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked

    }//GEN-LAST:event_jLabel15MouseClicked

    private void jTextFieldNomeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldNomeFocusLost
        jTextFieldNome.setText(jTextFieldNome.getText().toUpperCase());
        LimpaInformacao();
    }//GEN-LAST:event_jTextFieldNomeFocusLost

    private void jTextFieldNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeActionPerformed

    private void jTextFieldNomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNomeKeyPressed
        if (evt.getKeyCode() == evt.VK_ESCAPE) {
            //            jButton_Novo.setEnabled(true);;
            jButton_Salvar.setEnabled(false);
            //            MenuPrincipal.jButton_Meu_Foco.setText("lec2");
            //            MenuPrincipal.jButton_Meu_Foco.requestFocus();
            this.dispose();
        }
        if (evt.getKeyCode() == evt.VK_ENTER) {
            jTextFieldNome.setText(jTextFieldNome.getText().toUpperCase());
            jFormattedTextFieldCnpj.requestFocus();
        }

        if (evt.getKeyCode() == evt.VK_DOWN) {
            jTextFieldNome.setText(jTextFieldNome.getText().toUpperCase());
            jFormattedTextFieldCnpj.requestFocus();
        }
        if (evt.getKeyCode() == evt.VK_SPACE) {
            //            jTextFieldNome.setText(jTextFieldNome.getText().toUpperCase());
        }
        AjustaMeuNome();
    }//GEN-LAST:event_jTextFieldNomeKeyPressed

    private void jTextFieldDescricaoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldDescricaoFocusLost
        jTextFieldDescricao.setText(jTextFieldDescricao.getText().toUpperCase());
        LimpaInformacao();
    }//GEN-LAST:event_jTextFieldDescricaoFocusLost

    private void jTextFieldDescricaoInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jTextFieldDescricaoInputMethodTextChanged

        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDescricaoInputMethodTextChanged

    private void jTextFieldDescricaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldDescricaoKeyPressed
        if (evt.getKeyCode() == evt.VK_ESCAPE) {
            this.dispose();
        }
        if (evt.getKeyCode() == evt.VK_ENTER) {
            jFormattedTextFieldTelefone.requestFocus();
        }
        if (evt.getKeyCode() == evt.VK_DOWN) {
            jFormattedTextFieldTelefone.requestFocus();
        }
        if (evt.getKeyCode() == evt.VK_UP) {
            jFormattedTextFieldInscricao.requestFocus();
        }
    }//GEN-LAST:event_jTextFieldDescricaoKeyPressed

    private void jTextFieldDescricaoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldDescricaoKeyReleased

        if (evt.getKeyCode() == evt.VK_LEFT) {
            System.out.println("esq");
        } else if (evt.getKeyCode() == evt.VK_RIGHT) {
            System.out.println("dir");
        } else if (evt.getKeyCode() == evt.VK_CONTROL) {
            System.out.println("VK_CONTROL");
        } else {
            AjustaMeuDescricao();
        }
    }//GEN-LAST:event_jTextFieldDescricaoKeyReleased

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked

    }//GEN-LAST:event_jLabel16MouseClicked

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
//        VerificaMeuCep();
    }//GEN-LAST:event_jLabel19MouseClicked

    private void jTextFieldEnderecoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldEnderecoFocusLost
        jTextFieldEndereco.setText(jTextFieldEndereco.getText().toUpperCase());
        LimpaInformacao();
    }//GEN-LAST:event_jTextFieldEnderecoFocusLost

    private void jTextFieldEnderecoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldEnderecoKeyPressed
        if (evt.getKeyCode() == evt.VK_ESCAPE) {
            this.dispose();
        }
        if (evt.getKeyCode() == evt.VK_ENTER) {
            jTextFieldEndereco.setText(jTextFieldEndereco.getText().toUpperCase());
            jTextFieldNumero.requestFocus();
        }
        if (evt.getKeyCode() == evt.VK_DOWN) {
            jTextFieldEndereco.setText(jTextFieldEndereco.getText().toUpperCase());
            jTextFieldNumero.requestFocus();
        }
        if (evt.getKeyCode() == evt.VK_UP) {
            jTextFieldEndereco.setText(jTextFieldEndereco.getText().toUpperCase());
            jFormattedTextFieldTelefone.requestFocus();
        }

    }//GEN-LAST:event_jTextFieldEnderecoKeyPressed

    private void jTextFieldEnderecoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldEnderecoKeyReleased
        if (evt.getKeyCode() == evt.VK_LEFT) {
            System.out.println("esq");
        } else if (evt.getKeyCode() == evt.VK_RIGHT) {
            System.out.println("dir");
        } else {
            AjustaMeuEndereco();
        }
    }//GEN-LAST:event_jTextFieldEnderecoKeyReleased

    private void jTextFieldNumeroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldNumeroFocusLost
        if (jTextFieldNumero.getText().length() > 20) {
            jTextFieldNumero.requestFocus();
            jTextFieldNumero.setBackground(Color.red);
        } else {
            jTextFieldNumero.setBackground(Color.white);
        }
    }//GEN-LAST:event_jTextFieldNumeroFocusLost

    private void jTextFieldNumeroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNumeroKeyPressed
        if (evt.getKeyCode() == evt.VK_ESCAPE) {
            //            jButton_Novo.setEnabled(true);
            //            jButton_Salvar.setEnabled(false);
            //            MenuPrincipal.jButton_Meu_Foco.setText("lec2");
            //            MenuPrincipal.jButton_Meu_Foco.requestFocus();
            this.dispose();
        }
        if (evt.getKeyCode() == evt.VK_ENTER) {
            jFormattedTextFieldCep.requestFocus();
        }
        if (evt.getKeyCode() == evt.VK_DOWN) {
            jFormattedTextFieldCep.requestFocus();
        }
        if (evt.getKeyCode() == evt.VK_UP) {
            jTextFieldEndereco.requestFocus();
        }


    }//GEN-LAST:event_jTextFieldNumeroKeyPressed

    private void jTextFieldComplementoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldComplementoFocusLost
        jTextFieldComplemento.setText(jTextFieldComplemento.getText().toUpperCase());
        AjustaMeuComplemento();
        //        if (jTextFieldComplemento.getText().length() > 140) {
        //            jTextFieldComplemento.requestFocus();
        //            jTextFieldComplemento.setBackground(Color.red);
        //        } else {
        //            jTextFieldComplemento.setBackground(Color.white);
        //        }
    }//GEN-LAST:event_jTextFieldComplementoFocusLost

    private void jTextFieldComplementoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldComplementoKeyPressed
        if (evt.getKeyCode() == evt.VK_ESCAPE) {
            //            jButton_Novo.setEnabled(true);
            //            jButton_Salvar.setEnabled(false);
            //            MenuPrincipal.jButton_Meu_Foco.setText("lec2");
            //            MenuPrincipal.jButton_Meu_Foco.requestFocus();
            this.dispose();
        }
        if (evt.getKeyCode() == evt.VK_ENTER) {
            jTextFieldComplemento.setText(jTextFieldComplemento.getText().toUpperCase());
            jTextFieldBairro.requestFocus();
        }
        if (evt.getKeyCode() == evt.VK_DOWN) {
            jTextFieldComplemento.setText(jTextFieldComplemento.getText().toUpperCase());
            jTextFieldBairro.requestFocus();
        }
        if (evt.getKeyCode() == evt.VK_UP) {
            jTextFieldComplemento.setText(jTextFieldComplemento.getText().toUpperCase());
            jFormattedTextFieldCep.requestFocus();
        }

        //        if (jTextFieldComplemento.getText().length() > 140) {
        //            jTextFieldComplemento.requestFocus();
        //            jTextFieldComplemento.setBackground(Color.red);
        //        } else {
        //            jTextFieldComplemento.setBackground(Color.white);
        //        }
    }//GEN-LAST:event_jTextFieldComplementoKeyPressed

    private void jTextFieldComplementoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldComplementoKeyReleased
        if (evt.getKeyCode() == evt.VK_LEFT) {
            System.out.println("esq");
        } else if (evt.getKeyCode() == evt.VK_RIGHT) {
            System.out.println("dir");
        } else {
            AjustaMeuComplemento();
        }
    }//GEN-LAST:event_jTextFieldComplementoKeyReleased

    private void jTextFieldBairroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldBairroFocusLost
        jTextFieldBairro.setText(jTextFieldBairro.getText().toUpperCase());
        AjustaMeuBairro();
        //        if (jTextFieldBairro.getText().length() > 130) {
        //            jTextFieldBairro.requestFocus();
        //            jTextFieldBairro.setBackground(Color.red);
        //        } else {
        //            jTextFieldBairro.setBackground(Color.white);
        //        }
    }//GEN-LAST:event_jTextFieldBairroFocusLost

    private void jTextFieldBairroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldBairroKeyPressed
        if (evt.getKeyCode() == evt.VK_ESCAPE) {
            //            jButton_Novo.setEnabled(true);
            //            jButton_Salvar.setEnabled(false);
            //            MenuPrincipal.jButton_Meu_Foco.setText("lec2");
            //            MenuPrincipal.jButton_Meu_Foco.requestFocus();
            this.dispose();
        }
        if (evt.getKeyCode() == evt.VK_ENTER) {
            jTextFieldBairro.setText(jTextFieldBairro.getText().toUpperCase());
            jTextFieldCidade.requestFocus();
        }
        if (evt.getKeyCode() == evt.VK_DOWN) {
            jTextFieldBairro.setText(jTextFieldBairro.getText().toUpperCase());
            jTextFieldCidade.requestFocus();
        }
        if (evt.getKeyCode() == evt.VK_UP) {
            jTextFieldBairro.setText(jTextFieldBairro.getText().toUpperCase());
            jTextFieldComplemento.requestFocus();
        }

        //        if (jTextFieldBairro.getText().length() > 130) {
        //            jTextFieldBairro.requestFocus();
        //            jTextFieldBairro.setBackground(Color.red);
        //        } else {
        //            jTextFieldBairro.setBackground(Color.white);
        //        }
    }//GEN-LAST:event_jTextFieldBairroKeyPressed

    private void jTextFieldBairroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldBairroKeyReleased
        if (evt.getKeyCode() == evt.VK_LEFT) {
            System.out.println("esq");
        } else if (evt.getKeyCode() == evt.VK_RIGHT) {
            System.out.println("dir");
        } else {
            AjustaMeuBairro();
        }
    }//GEN-LAST:event_jTextFieldBairroKeyReleased

    private void jTextFieldCidadeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldCidadeFocusLost
        jTextFieldCidade.setText(jTextFieldCidade.getText().toUpperCase());
        AjustaMeuCidade();

        //        if (jTextFieldCidade.getText().length() > 130) {
        //            jTextFieldCidade.requestFocus();
        //            jTextFieldCidade.setBackground(Color.red);
        //        } else {
        //            jTextFieldCidade.setBackground(Color.white);
        //        }
    }//GEN-LAST:event_jTextFieldCidadeFocusLost

    private void jTextFieldCidadeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCidadeKeyPressed

        if (evt.getKeyCode() == evt.VK_ESCAPE) {
            //            jButton_Novo.setEnabled(true);
            //            jButton_Salvar.setEnabled(false);
            //            MenuPrincipal.jButton_Meu_Foco.setText("lec2");
            //            MenuPrincipal.jButton_Meu_Foco.requestFocus();
            this.dispose();
        }
        if (evt.getKeyCode() == evt.VK_ENTER) {
            jTextFieldCidade.setText(jTextFieldCidade.getText().toUpperCase());
            jButton_Salvar.requestFocus();
        }
        if (evt.getKeyCode() == evt.VK_DOWN) {
            jTextFieldCidade.setText(jTextFieldCidade.getText().toUpperCase());
            jTextArea_Observacao.requestFocus();
        }
        if (evt.getKeyCode() == evt.VK_UP) {
            jTextFieldCidade.setText(jTextFieldCidade.getText().toUpperCase());
            jTextFieldBairro.requestFocus();
        }

        //        if (jTextFieldCidade.getText().length() > 130) {
        //            jTextFieldCidade.requestFocus();
        //            jTextFieldCidade.setBackground(Color.red);
        //        } else {
        //            jTextFieldCidade.setBackground(Color.white);
        //        }
    }//GEN-LAST:event_jTextFieldCidadeKeyPressed

    private void jTextFieldCidadeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCidadeKeyReleased
        if (evt.getKeyCode() == evt.VK_LEFT) {
            System.out.println("esq");
        } else if (evt.getKeyCode() == evt.VK_RIGHT) {
            System.out.println("dir");
        } else {
            AjustaMeuCidade();
        }
    }//GEN-LAST:event_jTextFieldCidadeKeyReleased

    private void jTextArea_ObservacaoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextArea_ObservacaoFocusLost
        jTextArea_Observacao.setText(jTextArea_Observacao.getText().toUpperCase());
        if (jTextArea_Observacao.getText().length() > 160) {
            jTextArea_Observacao.requestFocus();
            jTextArea_Observacao.setBackground(Color.red);
        } else {
            jTextArea_Observacao.setBackground(Color.white);
        }
    }//GEN-LAST:event_jTextArea_ObservacaoFocusLost

    private void jTextArea_ObservacaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextArea_ObservacaoKeyPressed
        AjustaObservacao();
    }//GEN-LAST:event_jTextArea_ObservacaoKeyPressed

    private void jTextFieldNumeroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNumeroKeyReleased
        AjustaMeuNumero();
    }//GEN-LAST:event_jTextFieldNumeroKeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jFormattedTextFieldCnpj.setValue(null);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jFormattedTextFieldInscricao.setValue(null);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jFormattedTextFieldInscricaoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFormattedTextFieldInscricaoFocusLost
        String s = jFormattedTextFieldInscricao.getText();
        if (s == null) {
            jFormattedTextFieldInscricao.setValue(null);
        }
    }//GEN-LAST:event_jFormattedTextFieldInscricaoFocusLost

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        jFormattedTextFieldTelefone.setValue(null);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        jFormattedTextFieldCep.setValue(null);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jFormattedTextFieldCnpjKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFormattedTextFieldCnpjKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            jFormattedTextFieldInscricao.requestFocus();
        }
    }//GEN-LAST:event_jFormattedTextFieldCnpjKeyPressed

    private void jFormattedTextFieldInscricaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFormattedTextFieldInscricaoKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            jTextFieldDescricao.requestFocus();
        }
    }//GEN-LAST:event_jFormattedTextFieldInscricaoKeyPressed

    private void jFormattedTextFieldTelefoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFormattedTextFieldTelefoneKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            jTextFieldEndereco.requestFocus();
        }
    }//GEN-LAST:event_jFormattedTextFieldTelefoneKeyPressed

    private void jFormattedTextFieldCepKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFormattedTextFieldCepKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            jTextFieldComplemento.requestFocus();
        }
    }//GEN-LAST:event_jFormattedTextFieldCepKeyPressed

    private void jFormattedTextFieldCnpjFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFormattedTextFieldCnpjFocusLost
        String s = jFormattedTextFieldCnpj.getText();
        if (s == null) {
            jFormattedTextFieldCnpj.setValue(null);
        }
    }//GEN-LAST:event_jFormattedTextFieldCnpjFocusLost

    private void jFormattedTextFieldCepFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFormattedTextFieldCepFocusLost
        String s = jFormattedTextFieldCep.getText();
        if (s == null) {
            jFormattedTextFieldCep.setValue(null);
        }
    }//GEN-LAST:event_jFormattedTextFieldCepFocusLost

    private void jFormattedTextFieldTelefoneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFormattedTextFieldTelefoneFocusLost
        String s = jFormattedTextFieldTelefone.getText();
        if (s == null) {
            jFormattedTextFieldTelefone.setValue(null);
        }
    }//GEN-LAST:event_jFormattedTextFieldTelefoneFocusLost

    private void jTextFieldNomeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldNomeFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                EditCliente dialog = new EditCliente(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    public void Editar() {
        BEANS.setCliente_id(id_referencia);
        BEANS.setCliente_nome(jTextFieldNome.getText());
        BEANS.setCliente_cnpj(jFormattedTextFieldCnpj.getText());
        BEANS.setCliente_inscricao(jFormattedTextFieldInscricao.getText());
        BEANS.setCliente_descricao(jTextFieldDescricao.getText());
        BEANS.setCliente_telefone(jFormattedTextFieldTelefone.getText());
        BEANS.setCliente_endereco(jTextFieldEndereco.getText());
        BEANS.setCliente_no(jTextFieldNumero.getText());
        BEANS.setCliente_cep(jFormattedTextFieldCep.getText());
        BEANS.setCliente_complemento(jTextFieldComplemento.getText());
        BEANS.setCliente_bairro(jTextFieldBairro.getText());
        BEANS.setCliente_cidade(jTextFieldCidade.getText());
        BEANS.setCliente_observacao(jTextArea_Observacao.getText());
        BEANS.setCliente_status(1);
        BEANS.setCliente_usuario_id(Integer.parseInt(Menu.jLabelIdUsuario.getText()));
        DAO.Editar(BEANS);
        LimpaCampos();
        ListaCliente.jMenuItem4.doClick();
        this.dispose();
    }

    public void LimpaCampos() {
        jTextFieldNome.setText("");
        jFormattedTextFieldCnpj.setText("");
        jFormattedTextFieldInscricao.setText("");
        jTextFieldDescricao.setText("");
        jFormattedTextFieldTelefone.setText("");
        jTextFieldEndereco.setText("");
        jTextFieldNumero.setText("");
        jFormattedTextFieldCep.setText("");
        jTextFieldComplemento.setText("");
        jTextFieldBairro.setText("");
        jTextFieldCidade.setText("");
        jTextArea_Observacao.setText("");
        jTextFieldNome.requestFocus();
    }

    public void AjustaMeuDescricao() {
        String a = jTextFieldDescricao.getText();
        int b = 50;
        String texto = AjustaCampoGenerico(a, b);
        if (texto == null) {
        } else {
            jTextFieldDescricao.setText(texto);
        }
    }

    public void AjustaMeuNome() {
        String a = jTextFieldNome.getText();
        int b = 25;
        String texto = AjustaCampoGenerico(a, b);
        if (texto == null) {
        } else {
            jTextFieldNome.setText(texto);
        }

    }

    public void AjustaMeuEndereco() {
        String a = jTextFieldEndereco.getText();
        int b = 80;
        String texto = AjustaCampoGenerico(a, b);
        if (texto == null) {
        } else {
            jTextFieldEndereco.setText(texto);
        }
    }

    public void AjustaMeuNumero() {
        String a = jTextFieldNumero.getText();
        int b = 6;
        String texto = AjustaCampoGenerico(a, b);
        if (texto == null) {
        } else {
            jTextFieldNumero.setText(texto);
        }
    }

    public void AjustaMeuComplemento() {
        String a = jTextFieldComplemento.getText();
        int b = 100;
        String texto = AjustaCampoGenerico(a, b);
        if (texto == null) {
        } else {
            jTextFieldComplemento.setText(texto);
        }
    }

    public void AjustaMeuBairro() {
        String a = jTextFieldBairro.getText();
        int b = 100;
        String texto = AjustaCampoGenerico(a, b);
        if (texto == null) {
        } else {
            jTextFieldBairro.setText(texto);
        }
    }

    public void AjustaMeuCidade() {
        String a = jTextFieldCidade.getText();
        int b = 100;
        String texto = AjustaCampoGenerico(a, b);
        if (texto == null) {
        } else {
            jTextFieldCidade.setText(texto);
        }
    }

    public void AjustaObservacao() {
        String a = jTextArea_Observacao.getText();
        int b = 150;
        String texto = AjustaCampoGenerico(a, b);
        if (texto == null) {
        } else {
            jTextArea_Observacao.setText(texto);
        }
    }
 

    /// manipula edição
    public void Chama() {
        for (BeansCliente c : DAO.Chama(Rid)) {
            id_referencia = (c.getCliente_id());
            jTextFieldNome.setText(c.getCliente_nome());
            jFormattedTextFieldCnpj.setText(c.getCliente_cnpj());
            jFormattedTextFieldInscricao.setText(c.getCliente_inscricao());
            jTextFieldDescricao.setText(c.getCliente_descricao());
            jFormattedTextFieldTelefone.setText(c.getCliente_telefone());
            jTextFieldEndereco.setText(c.getCliente_endereco());
            jTextFieldNumero.setText(c.getCliente_no());
            jFormattedTextFieldCep.setText(c.getCliente_cep());
            jTextFieldComplemento.setText(c.getCliente_complemento());
            jTextFieldBairro.setText(c.getCliente_bairro());
            jTextFieldCidade.setText(c.getCliente_cidade());
            jTextArea_Observacao.setText(c.getCliente_observacao());
            jTextFieldNome.setText(c.getCliente_nome());
        }
    }

    /// Parte do edit
    public void RecebeId(int id) {
        Rid = "" + id;
        rid = id;
        //id_referencia = id;
//        jTextField1.setText(Rid);
        System.out.println("Usuario.EditUsuario.RecebeIdUsuario() --  " + rid);
    }

    ////  aqui faz a edição
    public void evento_Verifica() {
        if (jTextFieldNome.getText().trim().isEmpty()) {
            System.out.println("vazio 1");
            jTextFieldNome.requestFocus();
            JOptionPane.showMessageDialog(rootPane, "Este campo não pode estar vazio !");
        } else if (jTextFieldDescricao.getText().trim().isEmpty()) {
            System.out.println("vazio 2");
            jTextFieldDescricao.requestFocus();
            JOptionPane.showMessageDialog(rootPane, "Este campo não pode estar vazio !");
        } else {
            Editar();
        }

    }

    public String AjustaCampoGenerico(String a, int b) {
        BEANS.setTamanho(b);
        BEANS.setTexto(a);
        String texto = null;
        for (BeansCliente c : control.AjustaCampoGenerico(BEANS)) {
            int tamanho = c.getTamanho();
            if (tamanho == 1) {
                texto = (c.getTexto());
            }
            jLabelExibirInformacoes.setText(c.getInformacao());
        }
        return texto;
    }

    public void LimpaInformacao() {
        jLabelExibirInformacoes.setText("");
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton_Salvar;
    private javax.swing.JFormattedTextField jFormattedTextFieldCep;
    private javax.swing.JFormattedTextField jFormattedTextFieldCnpj;
    private javax.swing.JFormattedTextField jFormattedTextFieldInscricao;
    private javax.swing.JFormattedTextField jFormattedTextFieldTelefone;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabelExibirInformacoes;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea_Observacao;
    private javax.swing.JTextField jTextFieldBairro;
    private javax.swing.JTextField jTextFieldCidade;
    private javax.swing.JTextField jTextFieldComplemento;
    private javax.swing.JTextField jTextFieldDescricao;
    private javax.swing.JTextField jTextFieldEndereco;
    public static javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldNumero;
    // End of variables declaration//GEN-END:variables
}
