/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.Produto;

import ConectaBanco.ConexaoBD;
import ModeloBeans.BeansProduto;
import ModeloBeans.BeansUnidade;
import ModeloDao.DaoProduto;
import ModeloDao.DaoUnidade;
import Principal.Menu;
import View.Unidade.AddUnidade;
import java.awt.Frame;
import java.math.BigDecimal;
import java.text.NumberFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author edson
 */
public class AddProduto extends javax.swing.JDialog {
// Chama conexao

    ConexaoBD conex = new ConexaoBD();

// chama benas e dao
    BeansProduto BEANS = new BeansProduto();
    DaoProduto DAO = new DaoProduto();

// Campos internos
//    int id_referencia;
//    String cnpj;
//    String cep;
    String telefone;
    String item;
    String T;
    String prod;

    /**
     * Creates new form AddUsuario
     */
    public AddProduto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        LimpaCampos();
//        PreencheUnidade();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jT_produto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jC_unidade = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jF_valor = new javax.swing.JFormattedTextField();
        jF_ncm = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jT_descricao = new javax.swing.JTextArea();
        jF_min = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        jB_valor = new javax.swing.JButton();
        jB_ncm = new javax.swing.JButton();
        jB_min = new javax.swing.JButton();
        jLabelExibirInformacoes = new javax.swing.JLabel();
        jB_salvar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jC_categoria = new javax.swing.JComboBox<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Adicionar produto");
        setResizable(false);

        jPanel1.setToolTipText("");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Produto :");

        jT_produto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jT_produtoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jT_produtoFocusLost(evt);
            }
        });
        jT_produto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jT_produtoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jT_produtoKeyReleased(evt);
            }
        });

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Unidade");

        jC_unidade.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jC_unidadeItemStateChanged(evt);
            }
        });
        jC_unidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jC_unidadeKeyPressed(evt);
            }
        });

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Valor R$");

        jF_valor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,## 0.0000"))));
        jF_valor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jF_valorKeyPressed(evt);
            }
        });

        try {
            jF_ncm.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####.##.##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jF_ncm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jF_ncmKeyPressed(evt);
            }
        });

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("NCM");

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Descrição ");

        jT_descricao.setColumns(20);
        jT_descricao.setLineWrap(true);
        jT_descricao.setRows(5);
        jT_descricao.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jT_descricaoFocusLost(evt);
            }
        });
        jT_descricao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jT_descricaoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jT_descricaoKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jT_descricao);

        jF_min.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,###0.000"))));
        jF_min.setText("1,000");
        jF_min.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jF_minKeyPressed(evt);
            }
        });

        jLabel7.setText("Estoq. Min");

        jB_valor.setText(" ");
        jB_valor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_valorActionPerformed(evt);
            }
        });

        jB_ncm.setText(" ");
        jB_ncm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_ncmActionPerformed(evt);
            }
        });

        jB_min.setText(" ");
        jB_min.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_minActionPerformed(evt);
            }
        });

        jLabelExibirInformacoes.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabelExibirInformacoes.setForeground(new java.awt.Color(255, 0, 0));
        jLabelExibirInformacoes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelExibirInformacoes.setText("Informações adicionais");

        jB_salvar.setBackground(new java.awt.Color(0, 204, 0));
        jB_salvar.setText("Salvar");
        jB_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_salvarActionPerformed(evt);
            }
        });

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Categoria :");

        jC_categoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Uso interno", "Comun / Diversos", "Kit / Agrupado" }));
        jC_categoria.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jC_categoriaItemStateChanged(evt);
            }
        });
        jC_categoria.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jC_categoriaKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 533, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                            .addComponent(jC_unidade, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                            .addComponent(jF_valor))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jB_valor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jF_ncm, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jB_ncm)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jF_min, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jB_min))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jB_salvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelExibirInformacoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jT_produto)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jC_categoria, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jC_categoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jT_produto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jC_unidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jF_valor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jF_ncm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jB_valor)
                            .addComponent(jB_ncm)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jF_min, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jB_min))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelExibirInformacoes, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(jB_salvar)))
        );

        jMenu1.setText("Arquivo");

        jMenuItem1.setText("Atualizar unidade");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Adicionar unidade");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("jMenuItem3");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jC_unidadeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jC_unidadeItemStateChanged


    }//GEN-LAST:event_jC_unidadeItemStateChanged

    private void jB_valorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_valorActionPerformed
        jF_valor.setValue(null);
    }//GEN-LAST:event_jB_valorActionPerformed

    private void jB_ncmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_ncmActionPerformed
        jF_ncm.setValue(null);
    }//GEN-LAST:event_jB_ncmActionPerformed

    private void jB_minActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_minActionPerformed
        jF_min.setValue(null);
    }//GEN-LAST:event_jB_minActionPerformed

    private void jT_produtoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jT_produtoKeyPressed
        if (evt.getKeyCode() == evt.VK_ESCAPE) {
            this.dispose();
        }
        if (evt.getKeyCode() == evt.VK_ENTER) {
            jC_unidade.requestFocus();
        }
    }//GEN-LAST:event_jT_produtoKeyPressed

    private void jT_produtoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jT_produtoFocusGained
//Ajusta_Produto();        
    }//GEN-LAST:event_jT_produtoFocusGained

    private void jT_produtoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jT_produtoFocusLost
        jLabelExibirInformacoes.setText("");
    }//GEN-LAST:event_jT_produtoFocusLost

    private void jT_produtoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jT_produtoKeyReleased
        Ajusta_Produto();
    }//GEN-LAST:event_jT_produtoKeyReleased

    private void jT_descricaoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jT_descricaoFocusLost
        jLabelExibirInformacoes.setText("");
    }//GEN-LAST:event_jT_descricaoFocusLost

    private void jT_descricaoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jT_descricaoKeyReleased
        Ajusta_Observacao();
    }//GEN-LAST:event_jT_descricaoKeyReleased

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        PreencheUnidade();

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        AddUnidade add;
        Frame Menu = null;
        add = new AddUnidade(Menu, rootPaneCheckingEnabled);
        add.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jB_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_salvarActionPerformed
//        jC_unidade.add(this);
        VerificarCamposVazios();
    }//GEN-LAST:event_jB_salvarActionPerformed

    private void jC_unidadeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jC_unidadeKeyPressed
        if (evt.getKeyCode() == evt.VK_ESCAPE) {
            this.dispose();
        }
        if (evt.getKeyCode() == evt.VK_F5) {
            PreencheUnidade();
        }
        if (evt.getKeyCode() == evt.VK_ENTER) {
            jF_valor.requestFocus();
        }
    }//GEN-LAST:event_jC_unidadeKeyPressed

    private void jF_valorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jF_valorKeyPressed
        if (evt.getKeyCode() == evt.VK_ESCAPE) {
            this.dispose();
        }
        if (evt.getKeyCode() == evt.VK_ENTER) {
            jF_ncm.requestFocus();
        }
    }//GEN-LAST:event_jF_valorKeyPressed

    private void jF_ncmKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jF_ncmKeyPressed
        if (evt.getKeyCode() == evt.VK_ESCAPE) {
            this.dispose();
        }
        if (evt.getKeyCode() == evt.VK_ENTER) {
            jF_min.requestFocus();
        }
    }//GEN-LAST:event_jF_ncmKeyPressed

    private void jF_minKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jF_minKeyPressed
        if (evt.getKeyCode() == evt.VK_ESCAPE) {
            this.dispose();
        }
        if (evt.getKeyCode() == evt.VK_ENTER) {
            jT_descricao.requestFocus();
        }
    }//GEN-LAST:event_jF_minKeyPressed

    private void jT_descricaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jT_descricaoKeyPressed
        if (evt.getKeyCode() == evt.VK_ESCAPE) {
            this.dispose();
        }
        if (evt.getKeyCode() == evt.VK_ENTER) {
//             VerificarCamposVazios();
        }
    }//GEN-LAST:event_jT_descricaoKeyPressed

    private void jC_categoriaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jC_categoriaItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jC_categoriaItemStateChanged

    private void jC_categoriaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jC_categoriaKeyPressed
        if (evt.getKeyCode() == evt.VK_ESCAPE) {
            this.dispose();
        }
        if (evt.getKeyCode() == evt.VK_ENTER) {
            jT_produto.requestFocus();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jC_categoriaKeyPressed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
//        chama();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AddProduto dialog = new AddProduto(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    public void VerificarCamposVazios() {
        if (jF_valor.getText().trim().isEmpty()) {
            jF_valor.setText("0,000");
        }
        if (jF_min.getText().trim().isEmpty()) {
            jF_min.setText("1,000");
        }
        if (jT_produto.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Campo(s) vazio(s)");
            jT_produto.requestFocus();

        } else {
            jT_produto.setText(jT_produto.getText().toUpperCase());
            jT_descricao.setText(jT_descricao.getText().toUpperCase());

            Salvar();
        }
    }

    public void Salvar() {
        BeansUnidade unidade = (BeansUnidade) jC_unidade.getSelectedItem();
        int id_unidade = unidade.getId_unidade();
//        JOptionPane.showMessageDialog(rootPane,  " - " + id_unidade);

        BEANS.setProduto_categoria(jC_categoria.getSelectedIndex());
        BEANS.setProduto_nome(jT_produto.getText());
        BEANS.setProduto_unidade(id_unidade);
        String Valor = jF_valor.getText().replace(".", "").replace(",", ".");
        BEANS.setProduto_valor(Double.parseDouble(Valor));
        String Ncm = jF_ncm.getText().replace(".", "");
        Ncm = Ncm.trim();
        if (Ncm.trim().isEmpty()) {
            Ncm = "00000000";
        }
        BEANS.setProduto_ncm(Integer.parseInt(Ncm));
        String Min = jF_min.getText().replace(".", "").replace(",", ".");
        BEANS.setProduto_min(Double.parseDouble(Min));
        BEANS.setProduto_descricao(jT_descricao.getText());

        BEANS.setProduto_status(1);
        BEANS.setProduto_usuario_id(Integer.parseInt(Menu.jLabelIdUsuario.getText()));
        if (T.equals("1")) {
            DAO.Salvar(BEANS);
        } else if (T.equals("2")) {
            BEANS.setProduto_id(Integer.parseInt(prod));
            DAO.Editar(BEANS);
        } else {
            System.err.println("Erro");
        }
        LimpaCampos();
        ListaProduto.jMenuItem4.doClick();

        this.dispose();
    }

    public void LimpaCampos() {
        jT_produto.setText("");
        jF_valor.setText(null);
        jF_ncm.setText(null);
        jF_min.setText(null);
        jT_descricao.setText("");
        jT_produto.requestFocus();
        jLabelExibirInformacoes.setText("");
        jC_categoria.setSelectedIndex(1);
    }

    public void Ajusta_Produto() {

        String s = jT_produto.getText();
        String textoLimitado = s.length() <= 90 ? s : s.substring(0, 100);
        if (textoLimitado.length() >= 99) {
            jLabelExibirInformacoes.setText("Campo com limite execido!! Max. " + textoLimitado.length());
            jT_produto.setText(textoLimitado);
        } else {
            jLabelExibirInformacoes.setText("Conta caracteres " + s.length() + " de 100");
        }
    }

    public void Ajusta_Observacao() {

        String s = jT_descricao.getText();
        String textoLimitado = s.length() <= 150 ? s : s.substring(0, 150);
        if (textoLimitado.length() >= 149) {
            jLabelExibirInformacoes.setText("Campo com limite execido!! Max. " + textoLimitado.length());
            jT_descricao.setText(textoLimitado);
        } else {
            jLabelExibirInformacoes.setText("Conta caracteres " + s.length() + " de 150");
        }
    }

    public void evento_Verifica() {
//        if (jTextFieldNome.getText().trim().isEmpty()) {
//            System.out.println("vazio 1");
//            jTextFieldNome.requestFocus();
//            JOptionPane.showMessageDialog(rootPane, "Este campo não pode estar vazio !");
//        } else if (jTextFieldDescricao.getText().trim().isEmpty()) {
//            System.out.println("vazio 2");
//            jTextFieldDescricao.requestFocus();
//            JOptionPane.showMessageDialog(rootPane, "Este campo não pode estar vazio !");
//        } else {
//            Salvar();
//        }

    }

    public void PreencheUnidade() {
//        BeansUnidade
        jC_unidade.removeAllItems();
        DaoUnidade DAOU = new DaoUnidade();
        for (BeansUnidade u : DAOU.PreencheUnidade()) {
            jC_unidade.addItem(u);
        }
    }

    public void PreencheUnidadeB() {
//        BeansUnidade
        jC_unidade.removeAllItems();
        DaoUnidade DAOU = new DaoUnidade();
        for (BeansUnidade u : DAOU.PreencheUnidadeB((String) item)) {
            jC_unidade.addItem(u);
        }
    }

    public void chama(String Prod) {
        prod = Prod;
        DaoProduto daop = new DaoProduto();
        for (BeansProduto p : daop.Chama(prod)) {
            jT_produto.setText(p.getProduto_nome());
            jT_descricao.setText(p.getProduto_descricao());
            Double num1 = (p.getProduto_valor());
            BigDecimal df1 = new BigDecimal(num1);
            NumberFormat nf1 = NumberFormat.getInstance();
            nf1.setMinimumFractionDigits(4);
            nf1.setMaximumFractionDigits(4);
            String FormatoValorProd = nf1.format(df1);
            jF_valor.setText((FormatoValorProd));
            jC_categoria.setSelectedIndex(p.getProduto_categoria());
            jF_ncm.setText(String.valueOf(p.getProduto_ncm()));

            Double num2 = (p.getProduto_min());
            System.out.println(" p.getProduto_min()   -     "+p.getProduto_min());
            BigDecimal df2 = new BigDecimal(num2);
            NumberFormat nf2 = NumberFormat.getInstance();
            nf2.setMinimumFractionDigits(3);
            nf2.setMaximumFractionDigits(3);
            String FormatoMin = nf2.format(df2);
            jF_min.setText(FormatoMin);
            
            String d = String.valueOf(p.getProduto_unidade());
            System.out.println("-- " + d);
            item = String.valueOf(p.getProduto_unidade());
            PreencheUnidadeB();
        }

    }

    public void recebeTipo(String t) {
        T = t;
        if (T.equals("1")) {
            jB_salvar.setText("salvar");
        } else if (T.equals("2")) {
            jB_salvar.setText("salvar alteração");
            this.setTitle("Editar Item [" + prod + "] - Produto - [" + jT_produto.getText() + " ]");
        } else {
            System.err.println("Erro");
        }
        System.err.println("T = " + T);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_min;
    private javax.swing.JButton jB_ncm;
    private javax.swing.JButton jB_salvar;
    private javax.swing.JButton jB_valor;
    private javax.swing.JComboBox<String> jC_categoria;
    private javax.swing.JComboBox<Object> jC_unidade;
    private javax.swing.JFormattedTextField jF_min;
    private javax.swing.JFormattedTextField jF_ncm;
    private javax.swing.JFormattedTextField jF_valor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelExibirInformacoes;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jT_descricao;
    private javax.swing.JTextField jT_produto;
    // End of variables declaration//GEN-END:variables
}
