/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.Produto;

import ModeloBeans.BeansImagem;

import ModeloBeans.BeansKit;
import ModeloBeans.BeansProduto;
import ModeloBeans.BeansUnidade;
import ModeloDao.DaoImagem;
import ModeloDao.DaoKit;
import ModeloDao.DaoProduto;
import ModeloDao.DaoUnidade;
import Principal.Menu;
import java.io.File;
import java.math.BigDecimal;
import java.text.NumberFormat;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author edson
 */
public class EditProduto extends javax.swing.JFrame {

    // Chama conexao
//    ConexaoBD conex = new ConexaoBD();
// chama benas e dao
    BeansProduto BEANS = new BeansProduto();
    DaoProduto DAO = new DaoProduto();

    // Campos internos
    String item;
    String T;
    String prod;

    Double num1, num2;
    String FormatoValorProd, FormatoMin;

    DefaultListModel MODELO;
    DefaultListModel MODELOB;
    DefaultListModel MODELOIMG;

    // imagem
    String CaminhoImagem, NomeImagem;
    ImageIcon icon;

    /**
     * Creates new form EditProduto
     */
    public EditProduto() {
        initComponents();

        PreencheListaA();

        PreencheListaB();

        PreencheListaImagem();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jT_produto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jC_unidade = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jF_valor = new javax.swing.JFormattedTextField();
        jF_ncm = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jT_descricao = new javax.swing.JTextArea();
        jF_min = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        jB_valor = new javax.swing.JButton();
        jB_ncm = new javax.swing.JButton();
        jB_min = new javax.swing.JButton();
        jLabelExibirInformacoes = new javax.swing.JLabel();
        jB_salvar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jC_categoria = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        JLblFoto = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList_Img = new javax.swing.JList<>();
        jB_Salvar_Img = new javax.swing.JButton();
        jB_Editar_Img = new javax.swing.JButton();
        jB_Excluir_Img = new javax.swing.JButton();
        jB_Buscar_Img = new javax.swing.JButton();
        jB_Finalizar_Img = new javax.swing.JButton();
        jC_Img = new javax.swing.JComboBox<>();
        jC_Img_Caminho = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jT_Busca = new javax.swing.JTextField();
        jB_Buscar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList_A = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        jList_B = new javax.swing.JList<>();
        jB_Finalizar_Kit = new javax.swing.JButton();
        jC_listaA = new javax.swing.JComboBox<>();
        jC_listaB = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jB_Finalizar_Inf = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jT_InfoAdicional = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel5.setBackground(new java.awt.Color(153, 153, 255));
        jPanel5.setToolTipText("");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Produto :");

        jT_produto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jT_produtoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jT_produtoFocusLost(evt);
            }
        });
        jT_produto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jT_produtoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jT_produtoKeyReleased(evt);
            }
        });

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Unidade");

        jC_unidade.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jC_unidadeItemStateChanged(evt);
            }
        });
        jC_unidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jC_unidadeKeyPressed(evt);
            }
        });

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Valor R$");

        jF_valor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,## 0.0000"))));
        jF_valor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jF_valorKeyPressed(evt);
            }
        });

        try {
            jF_ncm.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####.##.##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jF_ncm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jF_ncmKeyPressed(evt);
            }
        });

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("NCM");

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Descrição ");

        jT_descricao.setColumns(20);
        jT_descricao.setLineWrap(true);
        jT_descricao.setRows(5);
        jT_descricao.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jT_descricaoFocusLost(evt);
            }
        });
        jT_descricao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jT_descricaoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jT_descricaoKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jT_descricao);

        jF_min.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,###0.000"))));
        jF_min.setText("1,000");
        jF_min.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jF_minKeyPressed(evt);
            }
        });

        jLabel7.setText("Estoq. Min");

        jB_valor.setText(" ");
        jB_valor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_valorActionPerformed(evt);
            }
        });

        jB_ncm.setText(" ");
        jB_ncm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_ncmActionPerformed(evt);
            }
        });

        jB_min.setText(" ");
        jB_min.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_minActionPerformed(evt);
            }
        });

        jLabelExibirInformacoes.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabelExibirInformacoes.setForeground(new java.awt.Color(255, 0, 0));
        jLabelExibirInformacoes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelExibirInformacoes.setText("Informações adicionais");

        jB_salvar.setBackground(new java.awt.Color(0, 204, 0));
        jB_salvar.setText("Salvar");
        jB_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_salvarActionPerformed(evt);
            }
        });

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Categoria :");

        jC_categoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Uso interno", "Comun / Diversos", "Kit / Agrupado" }));
        jC_categoria.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jC_categoriaItemStateChanged(evt);
            }
        });
        jC_categoria.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jC_categoriaKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jT_produto)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jC_categoria, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jB_salvar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 141, Short.MAX_VALUE)
                                .addComponent(jLabelExibirInformacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                    .addComponent(jC_unidade, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(44, 44, 44)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                                    .addComponent(jF_valor))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jB_valor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jF_ncm, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jB_ncm)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jF_min, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jB_min)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jC_categoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jT_produto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jC_unidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jF_valor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jF_ncm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jB_valor)
                            .addComponent(jB_ncm)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jF_min, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jB_min))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB_salvar)
                    .addComponent(jLabelExibirInformacoes, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Dados produto", jPanel5);

        jPanel3.setBackground(new java.awt.Color(255, 51, 51));

        JLblFoto.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jList_Img.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList_Img.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList_ImgMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jList_Img);

        jB_Salvar_Img.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jB_Salvar_Img.setText("Salvar");
        jB_Salvar_Img.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_Salvar_ImgActionPerformed(evt);
            }
        });

        jB_Editar_Img.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jB_Editar_Img.setText("Editar");
        jB_Editar_Img.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_Editar_ImgActionPerformed(evt);
            }
        });

        jB_Excluir_Img.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jB_Excluir_Img.setText("Excluir");
        jB_Excluir_Img.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_Excluir_ImgActionPerformed(evt);
            }
        });

        jB_Buscar_Img.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jB_Buscar_Img.setText("Buscar");
        jB_Buscar_Img.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_Buscar_ImgActionPerformed(evt);
            }
        });

        jB_Finalizar_Img.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jB_Finalizar_Img.setText("Finalizar");
        jB_Finalizar_Img.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_Finalizar_ImgActionPerformed(evt);
            }
        });

        jC_Img.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jC_Img_Caminho.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jB_Buscar_Img, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jC_Img_Caminho, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jC_Img, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jB_Salvar_Img, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jB_Editar_Img, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jB_Excluir_Img)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jB_Finalizar_Img))
                    .addComponent(JLblFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jB_Editar_Img, jB_Excluir_Img, jB_Salvar_Img});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(JLblFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jB_Salvar_Img)
                            .addComponent(jB_Editar_Img)
                            .addComponent(jB_Excluir_Img)
                            .addComponent(jB_Finalizar_Img)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jB_Buscar_Img)
                            .addComponent(jC_Img, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jC_Img_Caminho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Imagens produto", jPanel3);

        jPanel2.setBackground(new java.awt.Color(204, 153, 255));

        jT_Busca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jT_BuscaKeyPressed(evt);
            }
        });

        jB_Buscar.setText("Buscar");
        jB_Buscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jB_BuscarMouseClicked(evt);
            }
        });
        jB_Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_BuscarActionPerformed(evt);
            }
        });

        jList_A.setModel(new javax.swing.AbstractListModel<Object>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList_A.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList_AMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jList_A);

        jList_B.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList_B.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList_BMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jList_B);

        jB_Finalizar_Kit.setText("Finalizar kit");
        jB_Finalizar_Kit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_Finalizar_KitActionPerformed(evt);
            }
        });

        jC_listaA.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jC_listaB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jB_Finalizar_Kit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jT_Busca, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jB_Buscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jC_listaA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jC_listaB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 92, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jT_Busca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB_Buscar)
                    .addComponent(jC_listaA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jC_listaB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                    .addComponent(jScrollPane4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jB_Finalizar_Kit))
        );

        jTabbedPane1.addTab("Composição  Kit", jPanel2);

        jPanel4.setBackground(new java.awt.Color(0, 255, 204));

        jB_Finalizar_Inf.setText("Finalizar informações adicionais");
        jB_Finalizar_Inf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_Finalizar_InfActionPerformed(evt);
            }
        });

        jT_InfoAdicional.setColumns(20);
        jT_InfoAdicional.setRows(5);
        jScrollPane5.setViewportView(jT_InfoAdicional);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane5)
                    .addComponent(jB_Finalizar_Inf, javax.swing.GroupLayout.DEFAULT_SIZE, 592, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jB_Finalizar_Inf)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Informações adicionais", jPanel4);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jT_produtoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jT_produtoFocusGained
        //Ajusta_Produto();
    }//GEN-LAST:event_jT_produtoFocusGained

    private void jT_produtoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jT_produtoFocusLost
        jLabelExibirInformacoes.setText("");
    }//GEN-LAST:event_jT_produtoFocusLost

    private void jT_produtoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jT_produtoKeyPressed
        if (evt.getKeyCode() == evt.VK_ESCAPE) {
            this.dispose();
        }
        if (evt.getKeyCode() == evt.VK_ENTER) {
            jC_unidade.requestFocus();
        }
    }//GEN-LAST:event_jT_produtoKeyPressed

    private void jT_produtoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jT_produtoKeyReleased
        Ajusta_Produto();
    }//GEN-LAST:event_jT_produtoKeyReleased

    private void jC_unidadeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jC_unidadeItemStateChanged

    }//GEN-LAST:event_jC_unidadeItemStateChanged

    private void jC_unidadeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jC_unidadeKeyPressed
        if (evt.getKeyCode() == evt.VK_ESCAPE) {
            this.dispose();
        }
        if (evt.getKeyCode() == evt.VK_F5) {
            PreencheUnidade();
        }
        if (evt.getKeyCode() == evt.VK_ENTER) {
            jF_valor.requestFocus();
        }
    }//GEN-LAST:event_jC_unidadeKeyPressed

    private void jF_valorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jF_valorKeyPressed
        if (evt.getKeyCode() == evt.VK_ESCAPE) {
            this.dispose();
        }
        if (evt.getKeyCode() == evt.VK_ENTER) {
            jF_ncm.requestFocus();
        }
    }//GEN-LAST:event_jF_valorKeyPressed

    private void jF_ncmKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jF_ncmKeyPressed
        if (evt.getKeyCode() == evt.VK_ESCAPE) {
            this.dispose();
        }
        if (evt.getKeyCode() == evt.VK_ENTER) {
            jF_min.requestFocus();
        }
    }//GEN-LAST:event_jF_ncmKeyPressed

    private void jT_descricaoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jT_descricaoFocusLost
        jLabelExibirInformacoes.setText("  ");
    }//GEN-LAST:event_jT_descricaoFocusLost

    private void jT_descricaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jT_descricaoKeyPressed
        if (evt.getKeyCode() == evt.VK_ESCAPE) {
            this.dispose();
        }
        if (evt.getKeyCode() == evt.VK_ENTER) {
            //             VerificarCamposVazios();
        }
    }//GEN-LAST:event_jT_descricaoKeyPressed

    private void jT_descricaoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jT_descricaoKeyReleased
        Ajusta_Observacao();
    }//GEN-LAST:event_jT_descricaoKeyReleased

    private void jF_minKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jF_minKeyPressed
        if (evt.getKeyCode() == evt.VK_ESCAPE) {
            this.dispose();
        }
        if (evt.getKeyCode() == evt.VK_ENTER) {
            jT_descricao.requestFocus();
        }
    }//GEN-LAST:event_jF_minKeyPressed

    private void jB_valorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_valorActionPerformed
        jF_valor.setValue(null);
    }//GEN-LAST:event_jB_valorActionPerformed

    private void jB_ncmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_ncmActionPerformed
        jF_ncm.setValue(null);
    }//GEN-LAST:event_jB_ncmActionPerformed

    private void jB_minActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_minActionPerformed
        jF_min.setValue(null);
    }//GEN-LAST:event_jB_minActionPerformed

    private void jB_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_salvarActionPerformed
        //        jC_unidade.add(this);
        VerificarCamposVazios();
    }//GEN-LAST:event_jB_salvarActionPerformed

    private void jC_categoriaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jC_categoriaItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jC_categoriaItemStateChanged

    private void jC_categoriaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jC_categoriaKeyPressed
        if (evt.getKeyCode() == evt.VK_ESCAPE) {
            this.dispose();
        }
        if (evt.getKeyCode() == evt.VK_ENTER) {
            jT_produto.requestFocus();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jC_categoriaKeyPressed

    private void jB_Buscar_ImgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_Buscar_ImgActionPerformed
        CaminhoImagem = "";
        NomeImagem = "";
        imagem();
        String LocalImagem = "C:\\Users\\edson\\Pictures";
        LocalImagem = LocalImagem.replace("\\", "/");
        JFileChooser fc = new JFileChooser();
        fc = new JFileChooser(new File(LocalImagem));
        FileNameExtensionFilter filter = new FileNameExtensionFilter(
                "JPG & GIF Images", "jpg", "gif");  //Cria um filtro
        fc.setFileFilter(filter);  //Altera o filtro do JFileChooser
        int res = fc.showOpenDialog(null);

        if (res == JFileChooser.APPROVE_OPTION) {
            File arquivo = fc.getSelectedFile();

            try {
                CaminhoImagem = arquivo.getPath();
                NomeImagem = arquivo.getName();
                JLblFoto.setText("");
                imagem();
                System.out.println("CaminhoImagem " + CaminhoImagem);
                System.out.println("NomeImagem " + NomeImagem);

            } catch (Exception ex) {
                //(ex.printStackTrace().toString());
            }

        } else {
            JOptionPane.showMessageDialog(null, "Voce nao selecionou nenhum arquivo.");
        }
//        PreencheListaImagem();
    }//GEN-LAST:event_jB_Buscar_ImgActionPerformed

    private void jB_Salvar_ImgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_Salvar_ImgActionPerformed
//        CaminhoImagem = "";
        imagem();
        SalvarImagem();
    }//GEN-LAST:event_jB_Salvar_ImgActionPerformed

    private void jB_Finalizar_ImgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_Finalizar_ImgActionPerformed
        this.dispose();
    }//GEN-LAST:event_jB_Finalizar_ImgActionPerformed

    private void jList_AMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList_AMouseClicked
        if (evt.getClickCount() == 2) {
            int idprod = Integer.parseInt(prod);
            int a = jList_A.getSelectedIndex();
            jC_listaA.setSelectedIndex(a);
            int kitprod = 0;
            try {
                kitprod = Integer.parseInt((String) jC_listaA.getSelectedItem());
            } catch (Exception e) {
                kitprod = 0;
            }

            if (kitprod != 0) {
                BeansKit Bkit = new BeansKit();
                DaoKit Dkit = new DaoKit();
                Bkit.setId_produto(idprod);
                Bkit.setProduto_kit(kitprod);
                Dkit.Salvar(Bkit);
                PreencheListaA();
                PreencheListaB();
                jT_Busca.requestFocus();
            }
        }

    }//GEN-LAST:event_jList_AMouseClicked

    private void jList_BMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList_BMouseClicked
        if (evt.getClickCount() == 2) {
            int idprod = Integer.parseInt(prod);

            int a = jList_B.getSelectedIndex();
            jC_listaB.setSelectedIndex(a);
            int kitprod = 0;
            try {
                kitprod = Integer.parseInt((String) jC_listaB.getSelectedItem());
            } catch (Exception e) {
                kitprod = 0;
            }

            if (kitprod != 0) {
                BeansKit Bkit = new BeansKit();
                DaoKit Dkit = new DaoKit();
                Bkit.setId_kits(kitprod);
                Dkit.Deletar(Bkit);
                PreencheListaA();
                PreencheListaB();
            }
        }

    }//GEN-LAST:event_jList_BMouseClicked

    private void jB_BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_BuscarActionPerformed
        PreencheListaA();
        PreencheListaB();
        jT_Busca.requestFocus();
    }//GEN-LAST:event_jB_BuscarActionPerformed

    private void jT_BuscaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jT_BuscaKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            jB_Buscar.doClick();
        }
    }//GEN-LAST:event_jT_BuscaKeyPressed

    private void jB_BuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jB_BuscarMouseClicked
        if (evt.getClickCount() == 2) {
            jT_Busca.requestFocus();
            jT_Busca.setText("");
        }
        PreencheListaA();
        PreencheListaB();
    }//GEN-LAST:event_jB_BuscarMouseClicked

    private void jB_Finalizar_KitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_Finalizar_KitActionPerformed
        this.dispose();
    }//GEN-LAST:event_jB_Finalizar_KitActionPerformed

    private void jB_Finalizar_InfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_Finalizar_InfActionPerformed
        String s = jT_InfoAdicional.getText();
        s = s.toUpperCase();
        String textoLimitado = s.length() <= 400 ? s : s.substring(0, 400);
        String v = prod;

        int V = Integer.parseInt(v);
        jB_Finalizar_Inf.setLabel(textoLimitado);
        DaoProduto di = new DaoProduto();
        BeansProduto bi = new BeansProduto();
        bi.setProduto_id(V);
        bi.setProduto_informacao(textoLimitado);
        di.UpdateInformacoes(bi);
        this.dispose();
    }//GEN-LAST:event_jB_Finalizar_InfActionPerformed

    private void jList_ImgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList_ImgMouseClicked
        jC_Img_Caminho.setSelectedIndex(jList_Img.getSelectedIndex());
        jC_Img.setSelectedIndex(jList_Img.getSelectedIndex());
        System.out.println("jC_Img_Caminho -" + jC_Img_Caminho.getSelectedItem());
        System.out.println("jC_Img -" + jC_Img.getSelectedItem());
        JLblFoto.setText("");
        CaminhoImagem = (String) jC_Img_Caminho.getSelectedItem();
        NomeImagem = jList_Img.getSelectedValue();
        imagem();
        DesbloquearBotao();
    }//GEN-LAST:event_jList_ImgMouseClicked

    private void jB_Editar_ImgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_Editar_ImgActionPerformed
        AlterarImagem();
        LimpaImagem();
        PreencheListaImagem();
    }//GEN-LAST:event_jB_Editar_ImgActionPerformed

    private void jB_Excluir_ImgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_Excluir_ImgActionPerformed
        DeletarImagem();
        LimpaImagem();
        PreencheListaImagem();
    }//GEN-LAST:event_jB_Excluir_ImgActionPerformed
    public void imagem() {
        LimpaImagem();
        icon = new ImageIcon(CaminhoImagem);
        icon.setImage(icon.getImage().getScaledInstance(JLblFoto.getWidth(), JLblFoto.getHeight(), 1));
        JLblFoto.setIcon(icon);

        //PreencheListaImagem();
    }

    public void LimpaImagem() {
        String CaminhoImagemB = "";
        JLblFoto.setText("");
        icon = new ImageIcon(CaminhoImagemB);
        icon.setImage(icon.getImage().getScaledInstance(JLblFoto.getWidth(), JLblFoto.getHeight(), 1));
        JLblFoto.setIcon(icon);

    }

    public void SalvarImagem() {
        if (CaminhoImagem.isEmpty()) {
        } else {
            DaoImagem DImg = new DaoImagem();
            BeansImagem BImg = new BeansImagem();
            BImg.setCaminho_imagem(CaminhoImagem);
            BImg.setNome_imagem(NomeImagem);
            BImg.setId_imagem_produto(Integer.parseInt(prod));
            DImg.Salvar(BImg);
            PreencheListaImagem();
        }
    }

    public void AlterarImagem() {
        if (CaminhoImagem.isEmpty()) {
        } else {
            DaoImagem DImg = new DaoImagem();
            BeansImagem BImg = new BeansImagem();
            BImg.setCaminho_imagem(CaminhoImagem);
            BImg.setNome_imagem(NomeImagem);
            BImg.setId_imagem_produto(Integer.parseInt(prod));
            BImg.setId_imagem(Integer.parseInt((String) jC_Img.getSelectedItem()));
            DImg.Alterar(BImg);
            PreencheListaImagem();
        }
    }

    public void DeletarImagem() {
        if (CaminhoImagem.isEmpty()) {
        } else {
            DaoImagem DImg = new DaoImagem();
            BeansImagem BImg = new BeansImagem();

            BImg.setId_imagem(Integer.parseInt((String) jC_Img.getSelectedItem()));
            DImg.Deletar(BImg);
            PreencheListaImagem();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditProduto.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditProduto.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditProduto.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditProduto.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditProduto().setVisible(true);
            }
        });
    }
// aqui prdoduto

    public void VerificarCamposVazios() {
        if (jF_valor.getText().trim().isEmpty()) {
            jF_valor.setText("0,000");
        }
        if (jF_min.getText().trim().isEmpty()) {
            jF_min.setText("1,000");
        }
        if (jT_produto.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Campo(s) vazio(s)");
            jT_produto.requestFocus();

        } else {
            jT_produto.setText(jT_produto.getText().toUpperCase());
            jT_descricao.setText(jT_descricao.getText().toUpperCase());

            Salvar();
        }
    }

    public void Salvar() {
        BeansUnidade unidade = (BeansUnidade) jC_unidade.getSelectedItem();
        int id_unidade = unidade.getId_unidade();
//        JOptionPane.showMessageDialog(rootPane,  " - " + id_unidade);

        BEANS.setProduto_categoria(jC_categoria.getSelectedIndex());
        BEANS.setProduto_nome(jT_produto.getText());
        BEANS.setProduto_unidade(id_unidade);
        String Valor = jF_valor.getText().replace(".", "").replace(",", ".");
        BEANS.setProduto_valor(Double.parseDouble(Valor));
        String Ncm = jF_ncm.getText().replace(".", "");
        Ncm = Ncm.trim();
        if (Ncm.trim().isEmpty()) {
            Ncm = "00000000";
        }
        BEANS.setProduto_ncm(Integer.parseInt(Ncm));
        String Min = jF_min.getText().replace(".", "").replace(",", ".");
        BEANS.setProduto_min(Double.parseDouble(Min));
        BEANS.setProduto_descricao(jT_descricao.getText());

        BEANS.setProduto_status(1);
        BEANS.setProduto_usuario_id(Integer.parseInt(Menu.jLabelIdUsuario.getText()));
        if (T.equals("1")) {
            DAO.Salvar(BEANS);
        } else if (T.equals("2")) {
            BEANS.setProduto_id(Integer.parseInt(prod));
            DAO.Editar(BEANS);
        } else {
            System.err.println("Erro");
        }
        LimpaCampos();
        ListaProduto.jMenuItem4.doClick();

        this.dispose();
    }

    public void LimpaCampos() {
        jT_produto.setText("");
        jF_valor.setText(null);
        jF_ncm.setText(null);
        jF_min.setText(null);
        jT_descricao.setText("");
        jT_produto.requestFocus();
        jLabelExibirInformacoes.setText("");
        jC_categoria.setSelectedIndex(1);
    }

    public void Ajusta_Produto() {

        String s = jT_produto.getText();
        String textoLimitado = s.length() <= 90 ? s : s.substring(0, 100);
        if (textoLimitado.length() >= 99) {
            jLabelExibirInformacoes.setText("Campo com limite execido!! Max. " + textoLimitado.length());
            jT_produto.setText(textoLimitado);
        } else {
            jLabelExibirInformacoes.setText("Conta caracteres " + s.length() + " de 100");
        }
    }

    public void Ajusta_Observacao() {

        String s = jT_descricao.getText();
        String textoLimitado = s.length() <= 150 ? s : s.substring(0, 150);
        if (textoLimitado.length() >= 149) {
            jLabelExibirInformacoes.setText("Campo com limite execido!! Max. " + textoLimitado.length());
            jT_descricao.setText(textoLimitado);
        } else {
            jLabelExibirInformacoes.setText("Conta caracteres " + s.length() + " de 150");
        }
    }

    public void evento_Verifica() {
//        if (jTextFieldNome.getText().trim().isEmpty()) {
//           ("vazio 1");
//            jTextFieldNome.requestFocus();
//            JOptionPane.showMessageDialog(rootPane, "Este campo não pode estar vazio !");
//        } else if (jTextFieldDescricao.getText().trim().isEmpty()) {
//           ("vazio 2");
//            jTextFieldDescricao.requestFocus();
//            JOptionPane.showMessageDialog(rootPane, "Este campo não pode estar vazio !");
//        } else {
//            Salvar();
//        }

    }

    public void PreencheUnidade() {
//        BeansUnidade
        jC_unidade.removeAllItems();
        DaoUnidade DAOU = new DaoUnidade();
        for (BeansUnidade u : DAOU.PreencheUnidade()) {
            jC_unidade.addItem(u);
        }
    }

    public void PreencheUnidadeB() {
//        BeansUnidade
        jC_unidade.removeAllItems();
        DaoUnidade DAOU = new DaoUnidade();
        for (BeansUnidade u : DAOU.PreencheUnidadeB((String) item)) {
            jC_unidade.addItem(u);
        }
    }

    public void Exnum1(double a) {
        num1 = a;
        BigDecimal df1 = new BigDecimal(num1);
        NumberFormat nf1 = NumberFormat.getInstance();
        nf1.setMinimumFractionDigits(4);
        nf1.setMaximumFractionDigits(4);
        FormatoValorProd = nf1.format(df1);
    }

    public void Exnum2(double a) {
        num2 = a;
        BigDecimal df2 = new BigDecimal(num2);
        NumberFormat nf2 = NumberFormat.getInstance();
        nf2.setMinimumFractionDigits(3);
        nf2.setMaximumFractionDigits(3);
        FormatoMin = nf2.format(df2);
    }

    public void chama(String Prod) {
        prod = Prod;
        DaoProduto daop = new DaoProduto();
        for (BeansProduto p : daop.Chama(prod)) {
            jT_produto.setText(p.getProduto_nome());
            jT_descricao.setText(p.getProduto_descricao());

            num1 = (p.getProduto_valor());
            Exnum1(num1);
            jF_valor.setText((FormatoValorProd));
            jC_categoria.setSelectedIndex(p.getProduto_categoria());
            jF_ncm.setText(String.valueOf(p.getProduto_ncm()));

            num2 = (p.getProduto_min());
            Exnum2(num2);
            jF_min.setText(FormatoMin);

            String d = String.valueOf(p.getProduto_unidade());
            item = String.valueOf(p.getProduto_unidade());
            PreencheUnidadeB();
            PreencheListaImagem();
        }

    }

    public void recebeTipo(String t) {
        T = t;
        if (T.equals("1")) {
            jB_salvar.setText("salvar");
        } else if (T.equals("2")) {
            jB_salvar.setText("salvar alteração");
            this.setTitle("Editar Item [" + prod + "] - Produto - [" + jT_produto.getText() + " ]");
        } else {
            System.err.println("Erro");
        }
        System.err.println("T = " + T);
    }

    /// lista
    public void PreencheListaA() {
        String busca = "";
        busca = jT_Busca.getText();
        MODELO = new DefaultListModel();
        jList_A.setModel(MODELO);
        jC_listaA.removeAllItems();
        DaoKit Dkit = new DaoKit();
        for (BeansProduto A : Dkit.PreencheListaA(prod, busca)) {
            MODELO.addElement(A.getProduto_nome());
            jList_A.setModel(MODELO);
            int a = A.getProduto_id();
            jC_listaA.addItem(String.valueOf(a));
        }
        jC_listaA.setVisible(false);
        jC_listaB.setVisible(false);
    }
    /// lista

    public void PreencheListaB() {

        MODELOB = new DefaultListModel();
        jList_B.setModel(MODELOB);
        jC_listaB.removeAllItems();
        DaoKit Dkit = new DaoKit();
        for (BeansProduto B : Dkit.PreencheListaB(prod)) {
            MODELOB.addElement(B.getProduto_nome());
            jList_B.setModel(MODELOB);
            int b = B.getProduto_id();
            jC_listaB.addItem(String.valueOf(b));
//System.out.println("View.Produto.EditProduto.PreencheListaB() >"+B.getProduto_nome());
        }
    }

    public void PreencheTexto() {
        DaoProduto di = new DaoProduto();
        String n = String.valueOf(prod);
        String txt = di.RetornaInformacao(n);
        jT_InfoAdicional.setText(txt);
    }

    /// lista imagem
    public void PreencheListaImagem() {
        jC_Img_Caminho.setVisible(false);
        jC_Img.setVisible(false);
        MODELOIMG = new DefaultListModel();
        jList_Img.setModel(MODELOIMG);
        jC_Img.removeAllItems();
        jC_Img_Caminho.removeAllItems();
        DaoImagem DImg = new DaoImagem();
        for (BeansImagem A : DImg.PreencheListaI(prod)) {
            MODELOIMG.addElement(A.getNome_imagem());
            jList_Img.setModel(MODELOIMG);
            int a = A.getId_imagem();
            jC_Img.addItem(String.valueOf(a));
            String b = A.getCaminho_imagem();
            jC_Img_Caminho.addItem(String.valueOf(b));
        }
        BloquearBotao();
    }

    public void BloquearBotao() {
        jB_Editar_Img.setEnabled(false);
        jB_Excluir_Img.setEnabled(false);
        jB_Salvar_Img.setEnabled(true);
    }

    public void DesbloquearBotao() {
        jB_Editar_Img.setEnabled(true);
        jB_Excluir_Img.setEnabled(true);
        jB_Salvar_Img.setEnabled(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLblFoto;
    private javax.swing.JButton jB_Buscar;
    private javax.swing.JButton jB_Buscar_Img;
    private javax.swing.JButton jB_Editar_Img;
    private javax.swing.JButton jB_Excluir_Img;
    private javax.swing.JButton jB_Finalizar_Img;
    private javax.swing.JButton jB_Finalizar_Inf;
    private javax.swing.JButton jB_Finalizar_Kit;
    private javax.swing.JButton jB_Salvar_Img;
    private javax.swing.JButton jB_min;
    private javax.swing.JButton jB_ncm;
    private javax.swing.JButton jB_salvar;
    private javax.swing.JButton jB_valor;
    private javax.swing.JComboBox<String> jC_Img;
    private javax.swing.JComboBox<String> jC_Img_Caminho;
    private javax.swing.JComboBox<String> jC_categoria;
    private javax.swing.JComboBox<String> jC_listaA;
    private javax.swing.JComboBox<String> jC_listaB;
    private javax.swing.JComboBox<Object> jC_unidade;
    private javax.swing.JFormattedTextField jF_min;
    private javax.swing.JFormattedTextField jF_ncm;
    private javax.swing.JFormattedTextField jF_valor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelExibirInformacoes;
    private javax.swing.JList<Object> jList_A;
    private javax.swing.JList<String> jList_B;
    private javax.swing.JList<String> jList_Img;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextField jT_Busca;
    private javax.swing.JTextArea jT_InfoAdicional;
    private javax.swing.JTextArea jT_descricao;
    private javax.swing.JTextField jT_produto;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
